### ISSUE TITLE
chyba pri vypisani zoznamu

### ISSUE THREAD

**Issue by andrejb-dev** [kodi-czsk/plugin.video.sosac.ph#100]
Poslednych par dni mi sosac po veceroch blbne. V **serialoch mi nevypise zoznam dielov** (ale ani ziadnu chybu), **vo filmoch po zvoleni niektoreho pismena mi hodi chybu**. Log z tej chyby posielam v prilozenom subore, zacina to zhruba na riadku 700. Chybu z casti serialov som nezachytil, ale ak bude treba mozem skusit reprodukovat a prilozit.

[kodi.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/683209/kodi.txt)

**Comment by bbaronSVK** [comment]
pozri si #96 a budes vediet preco....

**Comment by andrejb-dev** [comment]
vdaka, budem sledovat, toto zatvaram
