### ISSUE TITLE
Reimplementacia komunikacie pomocou JSON suborov

### ISSUE THREAD

**Issue by lubo** [kodi-czsk/plugin.video.sosac.ph#102]
**POZNAMKA: Toto je issue pre vyvojarov, aby sme sa vedeli skoordinovat a sledovat vyvoj.**

Ahojte. Ako ste si mohli vsimnut v #96, prevadzkovatelia sosacu kazdy vecer postavia ich stranku prehraj.me za CloudFlare DDoS ochranu. To najma preto, ze v tychto hodinach sa vdaka pouzivatelom toho doplnu a doteraz velmi neefektivnej komunikacii generuje tolko trafficu, ze ich servery to skratka nevedia zvladat. Preto sa prevadzkovatel rozhodol, ze nam bude poskytovat pravidelne generovane JSON subory s realtime search-om, pomocou ktorych by sme mali vediet tento problem znacne redukovat optimalizaciou komunikacie. Tu teda pridavat zoznam dostupnych JSONov a prosim nasu milu komunitu, aby to niekto (aspon z casti) naimplementoval a poslal pull request. Serialy su este rozrobene a chyba search, takze budem posielat pripadne zmeny v komentaroch, nech vedia zainteresovany dostavat notifikacie.

http://tv.sosac.to/vystupy5981/souboryaz.json
http://tv.sosac.to/vystupy5981/souboryzanry.json
http://tv.sosac.to/vystupy5981/moviesmostpopular.json
http://tv.sosac.to/vystupy5981/moviesrecentlyadded.json
http://tv.sosac.to/vystupy5981/tvpismena/
http://tv.sosac.to/vystupy5981/serialy/
http://tv.sosac.to/vystupy5981/tvshowsmostpopular.json
http://tv.sosac.to/vystupy5981/tvshowsrecentlyadded.json
http://tv.sosac.to/jsonsearchapi.php?q=[query]

**Comment by lubo** [comment]
Opravili sa nejake problemy u serialov, boli pridane tvshowsmostpopular.json a tvshowsrecentlyadded.json a search.

**Comment by bbaronSVK** [comment]
ono mna zaujima ako sa generuje URL z "l" Lebo ak sa pouzije len "l" pre auth. tak vysledna URL nefunguje aj ked dostanem status OK. Resp. co treba kedy dat do GET parametru ```streamuj``` pri jednotlivych kvalitach. zatial co som len tak zbezne pozeral, tak je tam ```original```, ```hd``` a ```soundtrack```.
predpokladam, ze:
```original``` je asi ```SD``` kvalita (mozno aj ```kinorip``` a ```tvrip```
```hd``` je ```720p```
```soundtrack``` je mix dvoch streamov a potrebuje este zadat ```id``` ineho streamu...toto sa asi ale nebude pouzivat. Ak by sa dalo nejako objasnit generovanie URL na streamuj.tv tak by to pomohlo a urychlilo upravu.

**Comment by bbaronSVK** [comment]
a este jedna otazka: ako casto sa tie .json generuju? momentalne su niekolko dni stare exporty...tak aby to malo zmysel ;-)

**Comment by macicek86** [comment]
lidi, prosím, moc tomu nerozumím ale už šest dnu to tady sleduju a žádná změna ve vývoji. Nemáte někdo prosím aspoň častečně funkční doplněk ?

**Comment by lubo** [comment]
@bbaronSVK Kukni #98. Ze vraj by mali byt pravidelne negenerovane, ale nepoznam periodu :D A ci to ma zmysel ? Well, bud toto alebo nic. Ak by sme iba obisli CF ochanu, tak by zas prevadzkovatelia nasli ine paky a kto vie, kedy a cim by to skoncilo. Tu nam vychadzaju v ustrety aj ked nemusia, tak ak bude nejaky problem tak to s nimi mozem skusit vyresit.

@macicek86 Nehnevaj sa, ale vsetci sme studenti alebo pracujuci alebo aj studenti aj pracujuci ludia. Robime co mozeme. Aj ked tomu nerozumies, tak vzdy mas moznost porozumiet a prilozit ruku k dielu.

**Comment by Saljack** [comment]
Cau, dela na tom nekdo? Ja uz jsem to z tech JSONu dostal. Zatim mam teda jenom filmy. Ptam se jenom abych vedel, jestli to mam dotahnout nebo se na to vybodnout. Diky

**Comment by lzoubek** [comment]
@Saljack klidne to dotahni a/nebo otevri PR i v rozpracovane verzi. Vytvoril jsem branch [json-rewrite](https://github.com/kodi-czsk/plugin.video.sosac.ph/tree/json-rewrite) do ktere muzem mergovat novy kod a nasledne se pak vsechno mergne do masteru.

**Comment by Saljack** [comment]
Tak ok uz mam i serialy zitra to snad dorazim. Jenom doufam, ze ty JSONy budou aktualizovane jinak to byla prace k nicemu :-(. Ma k tomu nekdo nejake info? Jeste by bylo fajn, kdyby se struktura JSONu u serialu trochu upravila, ale to uz bychom chteli moc.

**Comment by Saljack** [comment]
Radeji jsem to v tom stavu v jakem je pushnul k sobe do repo, tak kdyby nekdo chtel tak to muze otestovat https://github.com/Saljack/plugin.video.sosac.ph pripadne prilozit ruku k dilu

**Comment by OndrejIT** [comment]
Nejak me unika smysl tehle ochrany od provozovatele, kdyz pouziva cf tak proc nezapne proxy ktera ma kes? Ale pokud je ten json aktualni tak je to pochopitelne lepsi nez parsovat wep. Btw taky klidne prilozim ruku k dilu, ale chtelo by to nasadit, nez se to poradne otestuje co to soupnout jako betu a mit tak sosace dva?

**Comment by Saljack** [comment]
@OndrejIT muzes to zkusit v mem repu staci preplacnout sosac.py a melo by to fungovat. 

Jinak co uz mam (resp. jsem vyzkousel):
- Prochazeni a prehravani filmu a serialu a vsech veci co jsou v json
- Zobrazovani coveru u vseho 
- Pridavani do favourites

Co zbyva:
- Jazyky tj. rozliseni cs en atp. zatim je vse v cs 
- Flagy
- Stahovani (to je mozna chyba resolveru)
- Vyhledavani
- Ruzna nastaveni pluginu
- Reverse u epizod

**Comment by macicek86** [comment]
skusil jsem verzi od @Saljack ale 

[kodi.log.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/694558/kodi.log.txt)

delam neco spatne?

**Comment by vladacr** [comment]
Verze od Saljack mi funguje jak v Kodi (RPi3), tak v xTrend 9500 (Enigma2). Skvělá práce. díky moc.

**Comment by Saljack** [comment]
Ok tak skoro vse by melo byt funkcni. Co nefunguje je popsano ve #103 . Budu moc rad, kdyz to zkusite a nahlasite chyby. 

Jinak vsimnul jsem si, ze JSON soubory jsou nove vygenerovane a tim mi teda spadnul velky kamen ze srdce ;-) 

@macicek86 zkus to prosim s nejnovejsi verzi u me vypada to, ze se nepovedlo nacist json file, ale netusim proc kdyztak bych tam pridal debug co se vubec stahlo.

**Comment by macicek86** [comment]
Bohužel novější verze je pro mě pase, jelikož mám na TV boxu android 4.4, ale před chvili sem si všiml že pokud do doplnku vstoupím přez Yates tak není problém

**Comment by Saljack** [comment]
@macicek86 Myslel jsem nejnovejsi verzi sosac.py ode me

**Comment by pv501977** [comment]
@Saljack Zkusil jsem tvoji verzi, pekna prace. 
Poznamky:
 - V okne Movies - by Genres jsou nazvy zanru psany velkymi pismeny a kde jsou hacky a carky, tak ty jsou malymi pismeny. Prvni pismeno by melo byt velke, dalsi male.
 - Nelze vlozit slozku Movies, TV Showes a konkretni film do Knihovny. Drive to slo.
 - Stahovani jde (Stream Resolver 1.6.47), nejde pokud byl cil SMB na siti
 - Nelze zobrazit filmy pod Movies - S, P 
 - Polozky v Movies nejsou serazeny dle abecedy - napr. znak N je jinde
 - Pokud jsou jiz filmy v Knihovne, tak je nelze prehrat

**Comment by Saljack** [comment]
- V okne Movies - by Genres jsou nazvy zanru psany velkymi pismeny a kde jsou hacky a carky, tak ty jsou malymi pismeny. Prvni pismeno by melo byt velke, dalsi male. FIXED
- Nelze zobrazit filmy pod Movies - S, P FIXED
- Polozky v Movies nejsou serazeny dle abecedy - napr. znak N je jinde FIXED

Co s knihovnou nevim. Byl bych rad, kdyby se tohohle nekdo chopil. Protoze jsem to nikdy nepouzil a vubec nevim jak to funguje. A tudiz nen knihovna pro me priorita.

**Comment by svacna** [comment]
Zkouším tvou verzi a nelze zobrazit filmy pod Movies - P

Písmeno S u Movies už je ok.

**Comment by Saljack** [comment]
@svacna muzu poprosit o kodi.log

**Comment by janpal** [comment]
@macicek86 taktiez mam android tv box s kitkatom  (4.4.2)  preco by najnovsia verzia sosacu nemala na kitkate fungovat?

**Comment by pio4ADay** [comment]
Beham kodi na raspberry na libre elec, jak to mam implementovat? Nebo cekam na update release.?

**Comment by Saljack** [comment]
Pro @pio4ADay a pro vsechny dalsi kteri chteji vyzkouset:

1. Nejprve si v addonech v kodi zazalohujte soubor abyste se k nemu pozdeji mohli vratit plugin.video.sosac.ph/resources/lib/sosac.py
2. sosac.py v addonech plugin.video.sosac.ph/resources/lib/sosac.py prepiste stejnym souborem z meho repizitare tj. https://raw.githubusercontent.com/Saljack/plugin.video.sosac.ph/master/resources/lib/sosac.py

**Comment by macicek86** [comment]
@janpal  myslel jsem novejsi verzi kodi, ta na KitKat nejde :(. funguje ti na androide nova verze sosace? 

@Saljack skusil jsem nejnovejsi verzi a vysledek stejný přes ui kodi se nikam nedostanu, kdyz ale spustim sosac primo v Yatse tak není problém. v logu  spusteno v UI, spusteno v Yatse a pak znovu v UI.

[spmc.log.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/695905/spmc.log.txt)

**Comment by janpal** [comment]
@macicek86 njn, ale v Kodi 16.1 vsetko ok, alebo nie? Skoda ze github zakazal priame message. Nevidim dovod spamovat tuto issue :-(

**Comment by Saljack** [comment]
Tak ja nevidim duvo, proc by to nemelo na 16.1 nejit testoval jsem to zatim jenom na 17 ale tipnul bych si, ze to nekdo na 16.1 urcite zkousel.
Mohl by nekdo potvrdit, ze to funguje na:
- Kodi 16.1
- Android 
- Android KitKat

**Comment by macicek86** [comment]
Já ne, viz log kodi 16.1 android KK,
@janpal to spamovani je na mne?

**Comment by svacna** [comment]
V příloze zasílám log. Je to testované na SPMC androidu 7.1. Dříve jsem se
k tomu nedostal. Teď nefunguje S a P u Movies.

Dne út 10. 1. 2017 9:37 uživatel Tomáš Poledný <notifications@github.com>
napsal:

**Comment by janpal** [comment]
@macicek86 to vobec nie... V minulosti na githube existovala moznost napisat spravu priamo userovi ktoru by som teraz vyuzil aby som obisile zbytocny ping pong v issue.  

Takze ak tomu dobre rozumiem, @macicek86 testoval sosac na Kodi 16.1 a skoncilo to s chybou.  Pod Kodi 17 nova verzia funguje. Vecer to skusim na kodi 16.1 pod windows 10 a android 4.4.2. Vysledok napisem

**Comment by Saljack** [comment]
@svacna priloha nedorazila pridej to prosim rovnou sem

**Comment by svacna** [comment]
Posílám log. 
[spmc . log.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/696222/spmc.log.txt)

**Comment by svacna** [comment]
Teď otestováno  na Beelink GT1 -  Android 6.0,kodi 17 - S a P u Movies  ok. 

Asi bude problém u kodi 16.1 - tam jsme to teď pustil a S a P u Movies nejede.

Jen pro doplnění  informací.

**Comment by pv501977** [comment]
Vcera na Kodi 16.1 (openelec) - RPI 2 to jelo. Udelam dalsi testy..

**Comment by lubo** [comment]
Ludia, toto nie je spravne mieto na na preberanie vysledkov testov. Toto je issue pre vyvojarov.

**Comment by pv501977** [comment]
Nelze zobrazit filmy pod Movies - P, ostatni OK
Stahovani nejde pokud ma film vice streamu - napr. Deepwater Horizon

**Comment by lubo** [comment]
Dostal som novu informaciu, ze tieto subory momentalne nie su aktualne, ale akonahle naimplementujeme tuto feature, tak sa budu automaticky regenerovat a budu dostupne pod tou istou URL.

**Comment by lzoubek** [comment]
PR s fuknční knihovnou #104

**Comment by janpal** [comment]
@Lubo kam teda pisat objavene bugy? Ku commitu?

@macicek86 po zmene sosac.py na androide 4.4.2 sosac nefunkcny. Po cistej instalacii Kodi 16.1 a sosacu, preplacnuti resources a odmazni pyo suborov vsetko funkcne aj pod androidom.

**Comment by lubo** [comment]
@janpal Ku aktualnej verzii do vlastnej issue, ku vyvojovej verzii zatial nema velky vyznam pisat bugy, kedze ta verzia je momentalne pod aktivnym vyvovojom. Ak mas bugy k nejakemu otvorenemu pull requestu, tak tam je na to priestor.

**Comment by pio4ADay** [comment]
@Lubo ja chapu ze kluci na tom makate jako divoky a fakt diky za to. Nebylo by mozne upnout link na add-on nebo repository na bud update nebo beta verzi aby se dal jednoduse instalovat na rsbp openelec ? Dik, a once again, good job guys.

**Comment by Saljack** [comment]
@pio4ADay můžeš si to udělat sám návod jak to vyzkoušet tu je o pár postů výše nebo prostě počkej

**Comment by ExSport** [comment]
Nevite jak casto se aktualizuji ty jsony? Ze posledni byl v sobotu.
Jsem myslel, ze diky nasazeni CloudFlare (CDN cachovani) to muzou generovat klidne denne bez vetsiho zatizeni vlastnich serveru :(
Dik

**Comment by lzoubek** [comment]
Hotovo - vypublikovana verze 1.3.0. Interval generovani je na domluve s provozovateli

**Comment by pio4ADay** [comment]
Izoubek takze uz je nova verze dostupna ?

**Comment by dusanmsk** [comment]
V akom je toto stave? Ticket je closed, ale skusal som to rozchodit uz niekolko krat (ako z branche tak z masteru) a vzdy koncim na nejake importy.

Momentalne (z masteru):
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named demjson
                                            Traceback (most recent call last):
                                              File "/home/msk/.kodi/addons/plugin.video.sosac.ph/service.py", line 24, in <module>
                                                from resources.lib.sosac import SosacContentProvider
                                              File "/home/msk/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 29, in <module>
                                                import util
                                              File "/home/msk/.kodi/addons/script.module.stream.resolver/lib/util.py", line 35, in <module>
                                                from demjson import demjson
                                            ImportError: No module named demjson

```

**Comment by bbaronSVK** [comment]
@dusanmsk nainstaluj z repa a bude ti to fungovat.

**Comment by bahamencz** [comment]
Taky bych se přidal. Čistá instalace 1.3.0 z repa a stejně sosáč nefunguje, buffering několik minut, objeví se chyba že cache je plná před načtením media, film běží pár minut a buffer znovu

**Comment by Saljack** [comment]
Tohle ale není chyba sosace podle stacktrace je to chyba v resolveru

**Comment by bbaronSVK** [comment]
resolver sa obcas zle updatne, aspon mne sa to uz par krat stalo, treba preinstalovat a malo by to byt ok. ten demjson je v zavislostiach, takze ak ho nenasiel, tak je problem s instalaciou. Treba to jednoducho znova nainstalovat a hlavne instalovat z repa ;-)
