### ISSUE TITLE
Jak se hromadně zbavit nastavení odběru seriálů?

### ISSUE THREAD

**Issue by dvovla** [kodi-czsk/plugin.video.sosac.ph#105]
Lze se nějak hromadně zbavit nastavení odběru seriálů? Díky!

**Comment by lzoubek** [comment]
Toto zatím není možné z pluginu. 

Lze to ale udělat smazáním `$KODI_PROFILE/temp/commoncache.db`

**Comment by dvovla** [comment]
Díky za odpověď, jakož i za všechnu tu práci na doplňku. Nevím jak byla funkce odběru zamýšlena, ale domnívám se, že by bylo dobré umožnit přidání všech seriálů do knihovny bez defaultního nastavení odběru. Tedy s možností jeho pozdějšího nastavení pouze u vybraných seriálů.

**Comment by ghost** [comment]
myslim ze @zbyna to ma uz vyriesene https://github.com/zbyna/plugin.video.sosac.ph/commits/master

**Comment by lzoubek** [comment]
Uz docela davno jsem zmenil vnitrni stukturu informaci o serialech, ktery se maji pravidelne scannovat tak, aby kazdemu z nich bylo mozne zmenit periodu scanu nebo ji uplne vypnout.

Co ma zbyna nevim, kdyz bude chtit, muze otevrit PR

**Comment by lzoubek** [comment]
Ve verzi 1.3.0 lze kompletne odber vycistit pomoci kontext menu "Remove All from library" dostupneho na vsech polozkach prvni urovne (Movies atd). Je treba to ale udelat v dobe, kdy zrovna nebezi obnova (Checking new content ...)

**Comment by dvovla** [comment]
Dobrý den všem a znovu díky za Vaši práci na doplňku.
Vyzkoušel jsem verzi 1.3.0 a stále nechápu logiku odběru seriálů.
- Přidám vše do knihovny - u všeho se nastaví odběr.
- Zruším tedy odběr u všech a nastavím si jej jen u vybraných titulů.
-  Aktualizuji knihovnu přidáním všech a opět se mi u všech nastaví odběr.
Dává to smysl?
Díky

**Comment by lzoubek** [comment]
Mě ano, když jsi opět přidal všechno, tak máš zase všechno.

Jaké chování by dávalo smysl?

Jestli chceš mít v knihovně všechno, ale nechceš aby se pravidelně hledal nový obsah

- Odeber vše z knihovny
- V nastavení pluginu nastav výchozí obnovu seriálů na 0
- Přidej vše do knihovny.

Když si následně nastavíš hodnotu jinak, bude platit pro nově přidané seriály. Zatím není možné nastavit si interval odběru u každé položky zvlášť, ale interně se tento interval ukládá ke každé položce

**Comment by dvovla** [comment]
Díky za reakci. 
Smysl knihovny (seriálů) ze Sosáče vidím v tom, že si člověk díky metadatům může vybrat titul který chce sledovat. Tedy je dobré aby byla aktuální co do titulů.
Kontrola a doplňování nových epizod mne zajímá jen u těch titulů, které sleduji.
Lze to? Díky!
PS. Vážně nejsem sám koho to zajímá.
