### ISSUE TITLE
opening stream dialog disable if PTVL running

### ISSUE THREAD

**Issue by ghost** [kodi-czsk/plugin.video.sosac.ph#11]
zdravim libor

nasiel som ako odstranit opening stream dialog ked je spustene pseudo tv live
treba pridat tento kod
info tu:

http://forums.tvaddons.ag/threads/32600-Disable-quot-Opening-Stream-quot-Option-possible?p=271172&viewfull=1#post271172

dialog sa nezobrazi ked sa pouzije tzv setResolvedUrl

bolo by super to implementovat do pluginu sosac

dakujem.
f.

**Comment by lzoubek** [comment]
`setResolvedUrl` pouzivame uz od zacatku, je to koneckoncu jediny zpusob, jak plugin muze oznamit kodi, ze ma neco k prehravani (jako vysledek akce, kdy kliknes na prehravane video)

prave zavolanim `setResolvedUrl` se spusti prehravani videa - kodi si vezme adresu streamu a zacne ji cist do bufferu. opening stream dialog vyskakuje bud proto, ze nasemu pluginu dlouho trva, nez url resolvne, nebo je to proto, ze se dlouho plni buffer videa.

**Comment by ghost** [comment]
aha tak mozno staci pridat len tento riadok...

PseudoTV = xbmcgui.Window(10000).getProperty('PseudoTVRunning')

lebo PTVL pouziva overlay tak je mozne ze tymto to okno posunie dozadu.

otestujem doma a dam vediet... Genesis a ine pluginy to maju vsebe takyto kod

**Comment by ghost** [comment]
no myslim ze to chce viac zmien kodu a dotoho sa teda nerozumiem tak ak by bol cas mozno by sa to mohlo skusit implementovat
dakujem
