### ISSUE TITLE
Force české názvy

### ISSUE THREAD

**Issue by Saljack** [kodi-czsk/plugin.video.sosac.ph#110]
Protože jsou filmy řazeny podle písmen, ale podle češtiny, tak by bylo dobré mít možnost v nastavení vynucení českých názvů.

**Comment by ghost** [comment]
len by som chcel podotknut ze vyuzivam imdb na scrape a klasicky kodi The Movie Database scraper tak aby to nebol problem potom dakujem

sosac plugin zevraj rozoznava lokalne nastavenie z kodi cz/en

**Comment by Saljack** [comment]
Pridal bych do nastaveni pluginu polozku "Force czech names" ktera by byla defaultne vypnuta a kdyz se zapne, tak pri prochazeni pluginu by byly nazvy filmu a serialu v cs.
Takze by v pripda, ze ma clovek nastaveny kodi v EN:

- Teenage Mutant Ninja Turtles
- Generation Earth
- Married with Children

ale

- Zelvy ninja
- Zeme stvorena lidmi 
- Zenaty se zavazky

Coz mi prijde vice logicke. Jeste me napada, ze by se ty filmy pripdane v EN mohli radit skutecne podle nazvu, tj ze pod Z by bylo:

- Generation Earth
- Married with Children
- Teenage Mutant Ninja Turtles

U tohohle bych ale chtel vedet jestli to tak chceme nebo ne?

**Comment by pstruh** [comment]
Nieje lepsie mat zoradene aj filmy/serialy v ENG podla abecedy ? Kto chce nastavi si  CS alebo ENG priamo v doplnku Sosaca.
Generation Earth - pod G
Married with Children - pod M
Teenage Mutant Ninja Turtles - pod T

v CS potom ako pises vyssie vsetko pod Z:
- Zelvy ninja
- Zeme stvorena lidmi
- Zenaty se zavazky

**Comment by Saljack** [comment]
@pstruh no to prave nejde filmy a serialy jsou v seznamech podle pismen podle cestiny. Tj. z.json obsahuje 
- Generation Earth
- Married with Children
- Teenage Mutant Ninja Turtles

Aby se to dalo seradit v EN podle pismen museli by se stahnout vsechny jsony s pismeny a nazvy potom seradit. Co jsem koukal na filmy, tak pismeno muze mit az 1MB tj. aby se zobrazilo pismeno je potreba stahnout 20MB a to se mi zda hodne a nevim jestli tohle delat kvuli sosaci, ktery s JSONami vysel hodne vstrict.

**Comment by ExSport** [comment]
@Saljack 
Movies maji kolem 2,7MB:
![image](https://cloud.githubusercontent.com/assets/1260408/22020584/55bc8314-dcb9-11e6-9589-5df78610524f.png)
TV serialy maji 1MB:
![image](https://cloud.githubusercontent.com/assets/1260408/22020825/84f87e20-dcba-11e6-9a32-5851a33e77ed.png)
Ale je fakt, ze dokud nebudou poskytovat separatni jsony pro EN a CS verze, nema to asi cenu jinak implementovat.
Btw. CouldFlare by jim mel v offloadovani statickych dat vyrazne pomoci. Pak by ani stahovani vsech json files nemusel byt problem...
