### ISSUE TITLE
select video source

### ISSUE THREAD

**Issue by ghost** [kodi-czsk/plugin.video.sosac.ph#111]
zdravim tak skusam 1.3 a stale sa ma pyta na kvalitu streamu ked spustim cokolvek
skusal som vydefaultovat settings a nic

dakujem

**Comment by pstruh** [comment]
U mna OK (Win10 - Kodi 17 RC3). Kvalitu aj jazyk prehra automaticky podla nastaveni....

![image](https://cloud.githubusercontent.com/assets/22531664/22042445/8ad648bc-dd0b-11e6-85bc-22dd6d71791c.png)

**Comment by ghost** [comment]
ok ďakujem za test asi updatnem kodi teda

**Comment by ghost** [comment]
ok pomohlo vymazat settings z addon_data

**Comment by OrbisPictus** [comment]
Ahojte, ja používam Kodi 16.1 (mám ho na viacerých zariadeniach), ale ja tam nevidím v "autoselect language" možnosť czech. Je tam len EN, any a vkladať titulky. A takisto tam nemám ten prepínač czech. Je to obmedzením verzie 16.1? Už som aj vymazal settings  z addon_data a nepomohlo. Akonáhle tam dám kvalitu "najlepšia" tak mi pustí video po anglicky.

**Comment by pstruh** [comment]
Kodi 16.1 taktiez bez problemov. Urcite mas poslednu ver sosaca 1.3.0 ?
![image](https://cloud.githubusercontent.com/assets/22531664/22044028/daa426f0-dd12-11e6-8abb-47ca68df2d00.png)

**Comment by OrbisPictus** [comment]
Áno mám. No nič skúsim to zajtra nejako rozchodiť. Skúsim odinštalovať a
nainštalovať na novo. Vďaka za odpoveď.

**Comment by OrbisPictus** [comment]
Tak som to odinštaloval, vymazal z kodi adresára všetky súbory čo mali niečo so sosáčom, nainštaloval a stále nič. Je to to isté ako predtým :( verzia je 1.3.0 z kodi-cz-sk repozitára. skúšal som stiahnuť aj z GITu, ale tvári sa to tak isto. možno je to len nejaká sprostosť v nastaveniach KODI, ktorá to nejako obmedzí. Netuším. Asi sa s tým zmierim :)
![snimka](https://cloud.githubusercontent.com/assets/25182804/22079606/c4cf7226-ddbc-11e6-986a-273a001e4992.JPG)

**Comment by lzoubek** [comment]
mas nastavenou kvalitu videa na "Zeptat se", proto se te to vzdycky pta.

Ale je mozne, ze se to zepta i pokud mas kvalitu nejlepsi. Zkus to otestovat na ruznych videich (kombinace vice kvalit a vice audiostop, nebo jedna audiostopa/kvalita)

**Comment by OrbisPictus** [comment]
tú kvalitu tak mám nastavenú preto, lebo ak tam dám "najlepšia" tak automaticky načíta ENG verziu. ak tam nastavím 720p a jazyk "any" tak načíta CZ jazyk. A momentálen pozerám jeden seriál, kde mi 720p v CZ neprehrá, tak musím púšťať 720p ENG,resp CZ v SD kvalite. Aj preto je tam teraz "spýtať sa" :) Ja sa len čudujem, prečo tam nemám tie nastavenie tak ako ich Pstruh.

**Comment by pstruh** [comment]
v SK lokalizacii Kodi je to zle prelozene
![image](https://cloud.githubusercontent.com/assets/22531664/22083762/b4751082-ddcd-11e6-949b-8d1d09a3b6d9.png)

**Comment by OrbisPictus** [comment]
:) tak to by ma nenapadlo :D ďakujem za pomoc. Už budem vedieť, čo mám nastaviť.
