### ISSUE TITLE
language - string id="30063"

### ISSUE THREAD

**Issue by pstruh** [kodi-czsk/plugin.video.sosac.ph#116]
V nastaveni sosaca je pouzite rovnake ID pre "Automaticky vyber jazyka" a pre moznost vkladania titulkov.
Je to rovnake pri ENG, CZ aj SK 

![image](https://cloud.githubusercontent.com/assets/22531664/22266451/6778aa34-e280-11e6-9036-5f20086aa167.png)

![image](https://cloud.githubusercontent.com/assets/22531664/22266333/f137867e-e27f-11e6-8a57-a1f65ebebc99.png)

**Comment by Saljack** [comment]
Co by vubec melo nastaveni Cestina delat?

**Comment by pstruh** [comment]
Ten prvy riadok je pre zobrazovanie titulkov ak su dostupne.

**Comment by lzoubek** [comment]
To by me taky zajimalo, k cemu to je a jak se to (ten prvni radek) do pluginu dostalo :-)

**Comment by Saljack** [comment]
Ja si toho vsimnul, kdyz jsem prepisoval na ten JSON. Navrhuji to zmenit na "Ceske titulky".

**Comment by pstruh** [comment]
V strings.xml to je definovane pod rovnakym id.
string id="30063" Česky
string id="30063" Vkládat titulky, jsou li k dispozici
