### ISSUE TITLE
Nenačítání titulků v Kodi 17

### ISSUE THREAD

**Issue by ToKroCZ** [kodi-czsk/plugin.video.sosac.ph#117]
Již několik verzí Kodi 17 přetrvává problém se Sosáčem, kdy se často po zapnutí streamu english+titulky pustí pouze anglický originál bez titulků. Nelze je nijak vynutit, jediné řešení je neustále vypínat a zapínat a na nějaký 5. pokus se to většinou chytí a titulky se načtou. Nevyhodí to žádnou chybovou hlášku, prostě se jen neukazují titulky. Problém je na Windows i na Android verzi stejný a přítomný napříč zařízeními. 

Na hlavním zařízení s Kodi 16 se vždy titulky bez problémů načtou. 

P.S. Nevím, jestli to má nějaký význam, ale na Kodi 17 používám nový defaultní skin Estuary.

**Comment by pstruh** [comment]
https://github.com/kodi-czsk/script.module.stream.resolver/issues/48

uprav si subory podla tohoto a pojdu ti :)
https://github.com/kodi-czsk/script.module.stream.resolver/pull/50

**Comment by ToKroCZ** [comment]
Díky, vyzkouším! A mohu se zeptat, proč to není opraveno normálním updatem? :D

**Comment by Saljack** [comment]
Protože ten timeout je šílený v tomhle PR

**Comment by ToKroCZ** [comment]
To jsem koukal no, ale pokud je to jediný způsob, jak to opravit, tak mi to pořád přijde (minimálně jako dočasný fix) lepší, než nefunkční titulky. Kodi 17 se blíží každým dnem, už je RC4.

**Comment by lzoubek** [comment]
Mam hotovou lepsi opravu, od Kodi 14 pridali do [API](https://codedocs.xyz/xbmc/xbmc/group__python__xbmcgui__listitem.html#ga1aa01919cb3006f9edf313f8d1f07b4c) lepsi moznost vlozeni cesty k titulkum (ten puvodni kod je dost stary workaround a byla to jedina cesta jak muze plugin titulky poskytovat). Musim to jen otestovat na 17ce

**Comment by ToKroCZ** [comment]
Skvěle, díky!

**Comment by lzoubek** [comment]
[PR](https://github.com/kodi-czsk/script.module.stream.resolver/pull/54) je na svete, otestoval jsem jak 16 tak 17 - titulky chodi. Kdo mate chvili, vyzkousejte mou verzi

**Comment by ToKroCZ** [comment]
@lzoubek Vyzkoušeno asi 8×, poznatky následující: 
6× jsem zapnul a nechal hrát, titulky vždy funkční
2× jsem zapnul a přetočil někam do půlky, titulky nefunkční vždy
Zkoušel jsem seriály i filmy. Používám Windows Store verzi Kodi na Win 10 Pro.

Edit: Nikdy jsem takhle netestoval nehotovou variantu, nevím, jestli jsem postupoval správně: Stáhl jsem si tady na githubu zip se stream resolverem, odinstaloval Sosáč, nainstaloval zip, nainstaloval Sosáč.

**Comment by pstruh** [comment]
u mna zatial vsetko OK, titulky natiahne bez problemov. Skusal som viac krat za sebou.
RPi2 Kodi 17 RC3 LibreELEC v7.95.1
Win10 Kodi 17 RC4

**Comment by ToKroCZ** [comment]
@pstruh A zkoušel si přetáčení? Respektive kliknutí na tu časovou osu krátce po startu přehrávání? To mi zatím selhává :(

**Comment by pstruh** [comment]
aj s pretacanim ok, titulky natiahne hned ako sa pusti video.

**Comment by ToKroCZ** [comment]
Znovu jsem to zkoušel, a opravdu to tak je. Pokud hned po tom, co se video otevře kliknu na osu a někam ho přetočím, titulky tam nejsou. Nejsou tam ani když ho nově pustím a dám "Pokračovat od 25:12:10". Ale když ho zapnu normálně od začátku a nechám ho hrát, tak tam titulky jsou se 100% jistotou.
Zřejmě tedy stačí počkat, než se načtou titulky (zobrazí první?) a pak se již přetáčet dá. Ale když prostě během vteřiny kliknu na osu, tak nejsou.

**Comment by lzoubek** [comment]
To bude nejspis problem v kodi. Protoze plugin stahne a nastavi titulky prehravaci jeste predtim, nez se zacne vubec prehravat. Jeste si s tim zkusim pohrat

**Comment by ToKroCZ** [comment]
Já bych chápal, kdyby se to nestáhlo,  když hned přetočím, než to vlastně začne pořádně hrát. Ale zvláštní je, že je to nestáhne ani po tom kliknutí na pokračovat, což se v Kodi 16 nedělo. 
Ale jako dá se s tím žít, ta nefunkčnost po návratu k nějakému času je trochu nepříjemná, ale rozhodně lepší, než současný stav. Každopádně díky za opravu :-).

**Comment by lzoubek** [comment]
Co se ti zobrazi v pripade, ze ty titulky nejdou a ty v prehravani jdes na titulky->toggle language?

**Comment by ToKroCZ** [comment]
Nic, protože tam titulky vůbec nejsou načtené, takže je ta nabídka zašedlá.
![bez nazvu](https://cloud.githubusercontent.com/assets/11914160/22407585/929176fa-e669-11e6-9904-18b390791e9b.jpg)

**Comment by lzoubek** [comment]
Hmm .. muzes paste konec logu?

**Comment by ToKroCZ** [comment]
Omlouvám se, ale nejsem schopen poznat, co je relevantní, tak to sem dávám celé.

http://pastebin.com/4mvh0Yxp

**Comment by lzoubek** [comment]
To je vpohode, podle logu to ale vypada, ze mas porad stary stream.resovler. V logu na r. 343 je hlaska "Downloading subtitles and load them to player..." ale po novu by tam mela byt "Downloading subtitles" a pak "Setting subtitles to playable item".

Zkus ho znovu cely prepsat [timto](https://github.com/lzoubek/script.module.stream.resolver/archive/set-subtitles.zip)

[muj log](http://paste2.org/JynayF7h) - nemelo by byt nutne zapinat debug log

**Comment by ToKroCZ** [comment]
Určitě mám ten nový, už jen proto, že pouštění od začátku funguje nyní bezchybně. Ale možná se to jen nějak nedokonale aktualizovalo?  Teď mám k dispozici jen android, ale zkusím to na něm. Dej mi chvíli.

**Comment by lzoubek** [comment]
je mozny, ze se to aktualizovalo - myslim, ze se mi to prave stalo taky. 17ku jsem spustil dnes poprve a uz jen to, ze musis povolit "Nezname zdroje" svedci o tom, ze asi hodne zamakali na bezpecnosti pluginu (napr. davalo by smysl hlidat aby jeden plugin nemohl prepsat kod jinemu)

**Comment by ToKroCZ** [comment]
Na Androidu nejsem schopen po čisté instalaci doplňků chybu opakovat. Zítra to zkusím i na Windows, ale na Androidu jsem měl předtím stejný problém, takže to fakt pravděpodobně bylo tím, že to chce natvrdo smazat a znovu nainstalovat. Takže snad to bude ok ;-) 

Co se týče té 17ky, myslím, že to jsou jen estetické změny. Na webu píšou, že neověřené doplňky mohou být nebezpečí, takže tam přidali tuhle hlášku. A ještě nějakou historii aktualizací či co, ale přímo o změně fungování napíšou nic.

**Comment by ToKroCZ** [comment]
Omlouvám se za zpoždění, vyzkoušeno po čisté instalaci i na Windows a funguje to bez problémů.
