### ISSUE TITLE
Buffering

### ISSUE THREAD

**Issue by grezom** [kodi-czsk/plugin.video.sosac.ph#118]
Preco buffering filmu vzdy vecer zasekne na 1,8MB a tam caka aj niekolko minut. Potom sa zacnu do cachce tahat dalsie data az do momentu, kedy to je dostatok na spustenie filmu.

**Comment by jose1711** [comment]
robi aj u mna a casto ma to donuti vybrat SD

**Comment by grezom** [comment]
A preco to nenacitava kontinualne, ale vzdy to ma na 1,8MB tu pauzu?

**Comment by hetros** [comment]
Podařilo se to už nějak někomu zlepšit? Mně ten sosáč bufferuje skoro pořád. Začalo to někdy začátkem roku. Dělá mi to doma tak i na chalupě (různá zařízení). Internet mám upc a na chalupě wifi 40mb. Dřív se mi to nikdy nestalo a teď se nemůžu ani dokoukat na jediný film.

**Comment by lubo** [comment]
Preto, ze vzdy vecer byvaju servery a siet pretazene. Toto v ziadnom ohlade nevyzera byt problem pluginu, ale serverov alebo poskytovatela internetoveho pripojenia.
