### ISSUE TITLE
Přejmenování na Sosáč.tv

### ISSUE THREAD

**Issue by ToKroCZ** [kodi-czsk/plugin.video.sosac.ph#119]
Je to jen kosmetický problém, ale jak se můžeme dočíst na webu „ Sosac.ph, sosac.to nyní na sosac.tv“. Zkrátka doména a používaný název je teď sosac.tv, takže by asi bylo dobré přejmenovat doplněk a změnit ikonku. Navíc nemají žádnou oficiální ikonku, takže teď je tam jen nějaký výřez ze stránky. Dovolil jsem si to překreslit v Inkscapu. Ale samozřejmě lze použít cokoliv jiného :)
Co na to @lzoubek a @Lubo?

![sosac](https://cloud.githubusercontent.com/assets/11914160/22517547/c8eb1494-e8a9-11e6-90d2-71f18e56bfa0.png)

**Comment by lzoubek** [comment]
Ikona s mi libi, klidne udelej PR. Ohledne prejmenovani doplnku - doplnek se jmenuje Sosáč, coz myslim, ze je OK. Prejmenovavat ID addonu mi prijde zbytecne

**Comment by lubo** [comment]
Zmena ID doplnku by sposobila neprijemnosti pouzivatelom, ktori by o tejto zmene nevedeli. I ked by som bol radsej, keby to bolo na poriaku, neodporucam to.

**Comment by ToKroCZ** [comment]
To já nemyslel aby se měnilo ID, spíš jestli je to někde v popisu, nebo tak. Ale asi ne, máte pravdu, je tam jen sosáč :). Udělám teda PR. Díky!
