### ISSUE TITLE
Chyba v sosac.py

### ISSUE THREAD

**Issue by YanisZefar** [kodi-czsk/plugin.video.sosac.ph#121]
V sosac.py je dobná chyba:

for letter in ['0-9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'e', 'h', 'i', 'j', 'k', 'l', 'm',
'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']:

Je tam 2x e.

**Comment by ToKroCZ** [comment]
Tak asi můžeš udělat PR ;)

**Comment by ToKroCZ** [comment]
Odstranil jsem jedno "e" a zahrnul do PR
