### ISSUE TITLE
Nekorektne generovane NFO pro Serialy

### ISSUE THREAD

**Issue by ExSport** [kodi-czsk/plugin.video.sosac.ph#124]
Po zavedeni json souboru bych vyradil ci upravil fce **getBBDB** a **getTVDB**:
https://github.com/kodi-czsk/plugin.video.sosac.ph/blob/master/resources/lib/sutils.py#L134
JSON jiz obsahuje linky na CSFD a IMDB, takze neni nutne se doptavat bbaron.sk stranek, ktery navic v nekterych pripadech zapricini spatne vygenerovany link na TVDB viz napr.
http://csfd.bbaron.sk/find.php?sosac=1&name=Castle+na+zabit%C3%AD+%282009%29
vrati nazev bez roku a proto nasledne generovany link na TVDB odkazuje na uplne neco jine:
http://thetvdb.com/api/GetSeries.php?seriesname=Castle&language=cs

Zde bych zkusil duverovat nazvu z JSONu kde je jak EN tak CS nazev vcetne roku.
Zajimave, ze TVDB dokaze vratit 3 ruzne zaznamy:
Spatny nalez:
http://thetvdb.com/api/GetSeries.php?seriesname=Castle&language=cs
Korektni nalez, v cestine:
http://thetvdb.com/api/GetSeries.php?seriesname=Castle%20na%20zabit%C3%AD&language=cs
Korektni nalez, ale v anglictine:
http://thetvdb.com/api/GetSeries.php?seriesname=Castle%202009&language=cs

Ale asi uplne nejlepe pouzit IMDB cislo z JSONu a link vytvorit pres nej 🥇 :
http://thetvdb.com/api/GetSeriesByRemoteID.php?imdbid=tt1219024&language=cs

**Comment by ExSport** [comment]
@bbaronSVK 
K cemu se vlastne odkazuje na tvuj server? :)
Minimalne z meho pohledu po zavedeni JSON to je zbytecne...
Dik

**Comment by bbaronSVK** [comment]
@ExSport ja som uz aj zabudol, ze tam nieco take je. Mal som pocit, ze je to uz prec. Budem len rad, ked to pojde prec, len mi to zatazuje server.

**Comment by ExSport** [comment]
Kod mam prepsany, jen jeste nebyl cas otestovat...

**Comment by ExSport** [comment]
Vyreseno v https://github.com/kodi-czsk/plugin.video.sosac.ph/pull/129
