### ISSUE TITLE
sosac URL

### ISSUE THREAD

**Issue by cukoun** [kodi-czsk/plugin.video.sosac.ph#127]
Po spuštení se plugin připojuje na URL tv.sosac.to a hazí to chybu internal server error. Neměl by se plugin spíše připojovat na tv.sosac.tv?

**Comment by Saljack** [comment]
Na tv.sosac.tv nejsou jsony. http://tv.sosac.to/vystupy5981/ dava json http://tv.sosac.tv/vystupy5981/ me presmeruje na http://tv.sosac.tv/cs/ . Takze url se mi zda spravna, ale mozna by to chtelo uverit primo u zdroje.

**Comment by E000001** [comment]
viz poslední příspěvek
