### ISSUE TITLE
Kodi 17

### ISSUE THREAD

**Issue by ok1xgi** [kodi-czsk/plugin.video.sosac.ph#130]
Po dnesnim upgrade na Kodi 17 prestal Sosac fungovat 😢

**Comment by pstruh** [comment]
v kodi 17 vsetko funguje ako ma

**Comment by ok1xgi** [comment]
![img_0827](https://cloud.githubusercontent.com/assets/25709834/22861038/f543976a-f10e-11e6-82df-eea8b2b99e6b.JPG)

Bezi mi to na Rpi3. Neco jsem sledoval, pak se spustila automaticka aktualizace a po ni doplnek nesel spustit. Ted jsem zjistil ze nejde vice doplnku. Takze problem bude nejde jinde. Ale netusim 😥😥😥

**Comment by lubo** [comment]
Reinstaloval si si vsetky doplnky ?

**Comment by ok1xgi** [comment]
Zkousel jsem je ty co nefunguji.... bez uspechu

**Comment by lubo** [comment]
Tak si skus reinstalovat vsetky, hlavne script.module.stream.resolver.

**Comment by Saljack** [comment]
Koukni do slozky /home/osmc/.kodi/addons jestli tam mas slozku script.module.simplejson

**Comment by ok1xgi** [comment]
Tak ten simplejson tam neni

**Comment by ok1xgi** [comment]
Tak jsem zaktualizoval stream.resolver a zda se ze to jede

Diky
