### ISSUE TITLE
Serialy s titulkami

### ISSUE THREAD

**Issue by cellentano** [kodi-czsk/plugin.video.sosac.ph#132]
Po poslednej aktualizacii nejdu prehrat videa s titulkami > chyba skriptu:sosac. Preinstalovanie addon ani instalacia starsich verzii nepomohlo.
AB Prismcube Ruby, XBMC 13.2

**Comment by Saljack** [comment]
Priloz sem prosim log. Koukam, zed mas pekne starou verzi Kodi.

**Comment by lubo** [comment]
Ahoj, pre-Kodi verzie uz nie su podporovane. Prosim, upgradni aspon na Kodi 15.

**Comment by cellentano** [comment]
Ahoj, problem je, ze XBMC 13.2 je portovany ako operacny system sat settop boxu. Vyrobca uz nema v plane upgrade firmware, takze updated neprichadza do uvahy. 
Log prilozeny, tak to ma mozno nasvedomi stream resolver ...

[xbmc.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/782928/xbmc.txt)

Update:
Po instalacii stream resolver 1.6.50 problem s titulkami vyrieseny.

**Comment by cellentano** [comment]
Ahoj, je nejaka sanca, ze stream resolver bude updatnuty alebo podpora XBMC 13.2 je definitivne ukocena ?

**Comment by lubo** [comment]
Ahoj, na podporu pre-Kodi verzii bolo treba jeden komponent tretej strany, ktory ale sposoboval problemy pouzivatelom novych verzii Kodi ako napr. Krypton. Kedze dnes uz takmer vsetci presli na Kodi a Kodi sa stalo daleko dostupnejsim ako XBMC, tak uz nemame v plane vynakladat extra usilie na to, aby nase pluginy bezali aj na XBMC.

Co sa konkretne tvojho problemu tyka, je mi to luto, ale zrejme bude lepsie sa zamysliet nad zaobstaranim si noveho settop boxu, pricom tento krat by bolo dobre si zaobstarat nejaky otvoreny, aby sa ti nestalo to co teraz.

**Comment by cellentano** [comment]
To si ma nepotesil :( Vdaka za info.
