### ISSUE TITLE
Spustiť doplnok cez príkazový riadok

### ISSUE THREAD

**Issue by tb3d** [kodi-czsk/plugin.video.sosac.ph#136]
Zdravím, 

nakoľko nie som odborník do Pythonu, chcel by som sa s vami poradiť. Ako by som mohol spustiť tento doplnok cez príkazový riadok? Napríklad, že by som do príkazu poslal ako parameter URL adresu (buď streamuj.tv alebo prehraj.me) a ono by mi to hneď vrátilo URL adresy streamu a tituliek, ktoré by som si mohol už ja stiahnuť? 

Ďakujem za rady a riešenia.

**Comment by lubo** [comment]
Ahoj, doplnok na toto nie je stavany a to co od neho chces ani nie je v jeho kompetencii. Vid. [script.module.stream.resolver](/kodi-czsk/script.module.stream.resolver).
