### ISSUE TITLE
Philips Android Tv - nespusti stream 

### ISSUE THREAD

**Issue by zdenci22** [kodi-czsk/plugin.video.sosac.ph#137]
Posledny mesiac aj viac mi nespusti stream. Skusal som to na na Kodi aj SPMC ale to iste.
[kodi.log.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/856093/kodi.log.txt)

**Comment by lubo** [comment]
Dostavas `Connection timed out`, to vyzera na problem s tvojou sietou.

**Comment by zdenci22** [comment]
Este skusim obist router a napojit to na priamo. Ale ide o to ze Exodus mi ide aj Youtube aplikacia v pohode.
Problem je so Sosacom a ani Befun nespusti stream.
Co som pozeral v logu tak tam s tym urllib2.py nemoze byt problem?

**Comment by zdenci22** [comment]
Tak napriamo bez routra to funguje.
Skusal som resetnut router , iny port na routri , pripojit TV cez wifi a stale to nejde.
Neviem co by som este mohol spravit.
Ale dakujem za nakopnutie.

**Comment by lubo** [comment]
Ako hovorim, je to siet, typol by som problem s routingom. Skus `$ tracepath www.streamuj.tv` a uisti sa, ze sa vies na ten server pripojit. Toto sa ale netyka nasich doplnkov, takze zatvaram.
