### ISSUE TITLE
Skript pre Youtube-DL

### ISSUE THREAD

**Issue by tb3d** [kodi-czsk/plugin.video.sosac.ph#138]
Zdravím, 

je nejakým spôsobom možné prepísať tento python skript pre Youtube-dl? Teda vytvoriť extractor... Vďaka.

**Comment by lubo** [comment]
Je, ale to nie je to, co chces. Vid. [streamujtvresolver.py](/kodi-czsk/script.module.stream.resolver/blob/master/lib/server/streamujtvresolver.py).
