### ISSUE TITLE
prehraj.me API

### ISSUE THREAD

**Issue by lubo** [kodi-czsk/plugin.video.sosac.ph#14]
Neviem, ze ci viete, ale prehraj.me nam ponuka i ked trocha chabe, ale stale pouzitelne public "API", s ktorym by sa aj dalo nieco spravit. Su dve verzie, jedna posiela odpovede v HTML a druha v XML.

Tu je zoznam XML endpointov:
[Filmy v XML podle roku](http://tv.prehraj.me/filmyxml.php)
[Naposledy pridane filmy v XML](http://tv.prehraj.me/filmyxml2.php)
[Serialy v XML](http://tv.prehraj.me/serialyxml.php)

Pri zobrazeni tychto endpointov v prehliadaci sa vam zobrazia HTML formy, takze verim, ze si viete vstupne metody a parametre pozret sami ;)

Dovod, pre ktory to tu rozoberam je aktualny stav tohoto doplnku. Jednak sa mi nezda prehladny (podla mna zbytocne listovanie podla 0-9 a-z a mozno aj recent a popular) a jednak ani rychly (parsovanie stranok a este k tomu regexami, nepouzivanie strankovania, ...).

Tak ma napadlo, ze co tak prepisat aspon nejaku cast doplnku tak, aby pouzival ich API. Zvysilo by to vykon, spolahlivost a efektivnost, nakolko cez ich API vieme ziskat daleko viacej informacii ovela pohodlnejsie a rychlejsie.
Na druhej strane, aby sme vedeli co najlepsie vyuzit vyssie uvedene pozitiva ich API tak by bolo nutne aj urcitym sposobom zmenit strukturu fungovania doplnku tak, aby sa viacej podobala ich API. To znamena odstranit listovanie podla 0-9 a-z (u filmou to nahradit rokom vydania) atd.

Co sa pripadnej prerabky tyka, nemal by som problem to spravit ja. Prv ale nez sa do niecoho pustim chcem poznat vas nazor.

**Comment by E000001** [comment]
Ahoj, přidám svůj názor :) Já právě listování přes 0-9 a-Z úplně miluju :) Je to pro mě snadnější, než používat nějaké kategorie a hledání. Zároveň jsem i rád, že to nemá zdlouhavé listování. Prostě si počkám, než se načte kompletní seznam a pak už jen rychle vyberu film. Jediné co mě tam štve, je to, že nejsou obsaženy filmy začínající na diakritiku, už jsem je oslovil, zda by to nešlo z jejich strany změnit. Zároveň plno lidí používá ono listovani a-Z a mají přes to přidané filmy v knihovně.

Každopádně využít jejich XML není špatný nápad, já už na to dříve také koukal, šlo by možná použít vylistování posledních přidanejch filmů, ale nevím, jestli to není až moc zdlouhavé. Muselo by se to stahovat asi někde na pozadí, aby to ty lidi nerušilo. (100 000 položek - http://tv.prehraj.me/filmyxml2.php?limit=100000&sirka=670&vyska=377&affid=174#)

Řazení podle roků moc neuznávám. Teď jsem například koukal na Amerického Snipera. Na Prehraj.me byl rok 2014, stejně tak na IMDB, ale na CSFD a FDB je zase rok 2015....

**Comment by lubo** [comment]
@E000001, vdaka za tvoj nazor.

Ja to listovanie tak nevnimam. Aby som sa priznal, zepouzivam tie kategorie ani listovanie ked mam search, pretoze search mi v idealnom pripade zuzi okruh itemov len na ten, ktory chcem a nemusim sa potom prehrabavat v dlhych listoch. Cize pridat este search je urcite treba.

Co sa tyka naposledy pridanych filmov, tak tam by som do toho asi nesiel. Loadovat naraz take mnozstvo dat vzhladom na to kolko to trva je nezmysel. Tam by jednoznacne trebalo implementovat strankovanie. Avsak, ich endpoint nema naimplementovane nieco ako offset parameter, takze s narastajucim cislom strany by narastalo aj mnozstvo dat, ktore by sme museli stiahnut a sparsovat, coz tiez nie je dobre. Tam by asi bolo vhodnejsie ostat pri parsovani stranky a len pridat strankovanie.

Problem s tym, ako dlho to trva ich serverom by sme by sme vedeli ciastocne vyriesit tak, ze budeme vygenerovane XML nejako rozumne cachovat, takze pomale to kvoli tomu stahovaniu bolo iba ked by to prvy krat stiahlo. Tu cache by bolo samozrejme nutne nejako rozumne invalidovat, napr. pri odchode z danej sekcie, kde sa dane XML pouziva, aby sa pri dalsom vstupe stiahlo znova.

U serialov je to vsak ine. Tam si myslim, ze by sme to a-Z mohli aj odstranit, pretoze zoznam ich serialov nie je tak dlhy. Ale aj keby nie, tak podla daneho pismena vieme pekne odfiltrovat pozadovane serialy zo serialoveho endpointu. Taktiez, ich serveru netrva moc dlho kym vygeneruje XML aj napr. pre Simpsonovcov a este keby sme tie XMLka cachovali ako som spominal vyssie, tak serialy by mohli byt fakt rychle.

Co vy na to ?

A btw, podla CSFD vysiel [American Sniper](http://www.csfd.cz/film/341884-americky-sniper/) v 2014 ;)

**Comment by E000001** [comment]
Toho snipera museli určitě teď změnit :D :D :D 

Jinak plno lidí třeba nepoužívá ani k XBMC klávesnici, takže je pak napsání vyhledávacího dotazu složitější. A když si vezmu, jak špatně funguje vyhledávání například na befun.cz, tak to je katastrofa :( To ale není problém doplňku, ale trapného vyhledávání přímo na stránkách befunu.

Se seriály souhlasím, pro ty by tato změna mohla být dobrá.

**Comment by lubo** [comment]
Nie, ten sniper je tam takto uz dlhsie. Pozeral som ho myslim ze pred mesiacom a uz vtedy tam bol rok 2014.

Ja ku Kodi tiez nepouzivam klavesnicu, ale stiahol som si [Kore](https://play.google.com/store/apps/details?id=org.xbmc.kore) a nemam problem :D Navyse, skusal som search na http://movies.prehraj.me a ten vyzera celkom dobre. Urcite to treba naimplementovat do plugin.

No a u tych serialov by si to ty @E000001 ako preferoval ? Nechat listovanie podla a-Z, odstranit to, alebo k nim pridat este kategoriu "Vsetky" ?

**Comment by lukasenkocz** [comment]
Podle mne by nepřehlednosti sosáče/prehraj.me z důvodu množství obsahu spíše pomohlo doplnění procházení obsahu dle kategorií a doplnění obrázků a popisků. To první by neměl být problém (sám jsem si i starší verzi upravil a bylo to OK), ale to druhé asi ano - neumím to ale posoudit. Další problém ale vidím nedostupnost filmů s diakritikou na začátku - např. seriál Řím nebo filmy o četníkovi. Sice by se to v novější verzi mělo řídit dle nastavení KODI (nezkoušel jsem), ale to mi přijde zdlouhavé. Nešlo by to aspoň dát přímo do nastavení pluginu nebo ještě lépe procházet v pluginu jak anglické, tak české názvy?

**Comment by lubo** [comment]
@lukasenkocz, nic z toho by nemal byt problem.

Je inac nutne podporovat aj anglictinu, ked tento plugin pouzivaju prakticky len cesi a slovaci ?

**Comment by lukasenkocz** [comment]
@Kuci: Pokud by byla podpora názvů s diakritikou na začátku, tak není angličtina samozřejmě nutná.

**Comment by lzoubek** [comment]
Navrhoval bych neco trosku jineho. 

Pokud mame zpusob jak vysosat vsechny serialy a filmy, nemel by byt zas takovy problem udelat jejich mirror a prizpusobit zobrazeni/karegorie tomu, co potrebuje plugin. Neznam nikoho ze strany sosace, ale myslim, ze to muzou jedine privitat, protoze se jejich webu znacne ulevi.

Tim mirrorem mam na mysli vpodstate staticke slozky/soubory, (nasadil bych to rovnou na github podobne jako http://kodi-czsk.github.io/library/befun.cz/) s tim, ze bychom pridali indexy pro plugin v JSON/XML formatu.

**Comment by lubo** [comment]
Vidim, ze v tejto chvili je uz pouzivate vsetko co sa dalo, dobra praca ludia.
