### ISSUE TITLE
Nefunkčnost přehrávání 

### ISSUE THREAD

**Issue by DrazekV** [kodi-czsk/plugin.video.sosac.ph#148]
Doplněk přestal načítat videa. Vždy vypíše jen: Nelze získat video link zkontrolujte jestli video nebylo odstraněno

**Comment by Tadji** [comment]
zdravim, také mi nefunguje prehravani videí ze sosace přes kodi. Video na streamujTV je a přes web browser přehrání videa funguje. 
Kodi: 17.4
Sosac: 1.3.6

prikladam log:
[kodi_sosac_log.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/1351587/kodi_sosac_log.txt)

**Comment by peekaa** [comment]
Jen sem vložím odkaz na relevantní komenty z xbmc: http://www.xbmc-kodi.cz/prispevek-nefunk%C4%8Dn%C3%AD-sos%C3%A1%C4%8D-%C5%99e%C5%A1en%C3%AD?pid=30779#pid30779

**Comment by lzoubek** [comment]
Opraveno ve verzi 1.3.7 (vyjde v 21:00) - nefunkčnost byla způsobena vypnutím pomocné služby, která byla dříve používána pro obcházení zabezpeční (před přechodem na HTML5 videa). Nyní služba už není třeba.
