### ISSUE TITLE
Sosac chyba skriptu

### ISSUE THREAD

**Issue by mukates** [kodi-czsk/plugin.video.sosac.ph#15]
Dobry den, pri pouzivani pluginu sosac v. 1.1.0 mam problem s tym, ze mi v plugine funguje iba listovanie v kategoriach: Movies-Most popular, TV Shows- Most popular, Movies-Recently added, TV Shows-Recently aded. Pokial vyberiem polozky: Movies alebo TV shows, nabehne mi len "chyba skriptu". Pripajam vypis z logu:

20:35:15 T:855774304   DEBUG: emyeo :: OnJobComplete 426  this = 0x168eaf8,
20:35:15 T:855774304   DEBUG: emyeo :: Process 61  this = 0x2a6c8b0,
20:35:15 T:855774304   DEBUG: LAEL98 DEBUG NEXTJOB
20:35:15 T:855774304   DEBUG: emyeo :: GetNextJob::366-- this = 0x2a6c8b0, m_jobEvent.signaled 0 , m_jobEvent.numWaits 0
20:35:15 T:717590528   ERROR: GetDirectory - Error getting plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=687474703a2f2f6d6f766965732e7072656872616a2e6d65
20:35:15 T:717590528   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=687474703a2f2f6d6f766965732e7072656872616a2e6d65) failed
20:35:15 T:717590528   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.sosac.ph/)
20:35:15 T:717590528   DEBUG:   ParentPath = [plugin://plugin.video.sosac.ph/]
20:35:15 T:717590528   DEBUG: Loading items: 7, directory: plugin://plugin.video.sosac.ph/ sort method: 0, ascending: false
20:35:15 T:833410144   DEBUG:   -- items: 1418, sort method: 1, ascending: true
20:35:15 T:833410144   DEBUG: Building UPnP response with filter '@id,@parentID,@restricted,@childCount,dc:title,dc:creator,upnp:artist,upnp:class,dc:date,upnp:album,upnp:genre,res,res@size,res@duration,res@protection,res@bitrate,res@resolution,res@protocolInfo,res@nrAudioChannels,res@sampleFrequency,upnp:albumArtURI,upnp:albumArtURI@dlna:profileID, res@dlna:cleartextSize', starting @ 340 with 10 requested

Zariadenie: Prismcube, original firmware 2.0.4, XBMC verzia 13.2.

Dakujem za akykolvek napad.
S pozdravom Michal

**Comment by lzoubek** [comment]
ahoj, 

zapnuty debug neni moc potreba, spis potrebujem ten log delsi (klidne od zacatku pusteni XBMC) a prinuceni pluginu spadnout. Z toho, co jsi poslal zatim nic moc zjistit nemuzu

**Comment by mukates** [comment]
OK, ak nemam zapnuty debug, tak  neviem najst ziadny pouzitelny log. Vo /var/log/ do kopy nic nieje. Iba par log suborov, ktore ale nesuvisia s danym problemom. Tu je link na kompletny vypis logu cez debug od restartu boxu az po chybu skriptu: http://www.bjservis.sk/xbmclog.txt

**Comment by lzoubek** [comment]
Diky za log. Oprava vyadana a objevi se ve verzi 1.2.0.

**Comment by mukates** [comment]
Super! Dakujem.

**Comment by mukates** [comment]
Ahoj. nainstaloval som v. 1.2.0 a teraz u plugin nejde spustit vobec :(

**Comment by lzoubek** [comment]
tak prosim o dalsi log

**Comment by mukates** [comment]
Link na log: http://www.bjservis.sk/xbmcsosac120.log
Pri verzii 1.2.0 mi xbmc vyhodi "chyba skriptu" uz pri pokuse o jeho spustenie.

**Comment by lzoubek** [comment]
vyzkousej prosim jeste verzi 1.2.1 (mela by byt uz dostupna) .. vcera jsem zapomnel releasnout stream.resolver, ktery obsahuje opravy chyby.

**Comment by mukates** [comment]
1.2.1 funguje ok. Dakujem.
