### ISSUE TITLE
Písmeno "P"- chyba

### ISSUE THREAD

**Issue by Vasek79** [kodi-czsk/plugin.video.sosac.ph#154]
Při procházení videotéky filmů se při pokusu o otevření písmene "P" objeví chyba a adresář se neotevře - zůstane na procházení písmen. Zkoušel jsem všechna ostatní písmena a ta byla OK, stejně tak v procházení seriálů není problém a to ani u "P". 
**Chyba je jen u písmene "P" u filmů.**
V přiloženém souboru je část logu, která se týká Sosáče.
[sosac_P.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/1976953/sosac_P.txt)

Mám dvě zařízení (RPI2, RPI3) a na obou se to chová stejně a podle diskuzí na netu se to neděje jen u mě.
S pozdravem Burian

**Comment by Petr325** [comment]
Potvrzuji stejný problém RPi 3 (LibreELEC), písmeno **P** u filmů nefunkční, jinak super doplněk, děkujeme .
