### ISSUE TITLE
Add all videos bere v potaz i filter

### ISSUE THREAD

**Issue by Saljack** [kodi-czsk/plugin.video.sosac.ph#158]
Je mozne ze tento posledny update ovplyvnil funkciu "add all to library" pre movies?https://pastebin.com/iZqBFwPp

Metody library_list_all_videos library_list_recent_videos a jejich volani metody list_videos obsahuji i polozku filter.

**Comment by xDereCx** [comment]
neviem ci sa rozumieme, ale v kazdom pripade mi to nebezi od posledneho update. ked ides na plugin sosac, potom movies, menu a "add all to library",
