### ISSUE TITLE
Doplněk přestal fungovat

### ISSUE THREAD

**Issue by ToKroCZ** [kodi-czsk/plugin.video.sosac.ph#17]
Doplněk Sosáč přestal fungovat, při pokusu o přístup do Popular Movies nebo pod písmeno v abecedním řazení se ukáže "Chyba skriptu". Kodi 14.2, Ubuntu, do teď funkční.

**Comment by E000001** [comment]
Od rána jim nefunguje web. Ještě včera vše fungovalo. Nezbývá, než čekat.

**Comment by ToKroCZ** [comment]
Díky za info.
