### ISSUE TITLE
Nefunkcni nektere serialy + Razeni dle zanru?

### ISSUE THREAD

**Issue by powerczech** [kodi-czsk/plugin.video.sosac.ph#18]
Zdravim,
1) bylo by mozne opravit nefunkcnost nekterych serialu (napr. Pravidla zasnoubeni - Rules of Engagement) - nefunguji pri vyberu podle abecedy, z hledani podle "date added" funguji.
2) v razeni "date added" se nezobrazuji vsechna videa (jen nektera) + seznam se nacita dlouho
3) bylo by mozne pridat razeni podle zanru? (komedie, drama...)
Diky.
Powerczech

**Comment by ghubber-zz** [comment]
2) bere se pouze prvni radek novinek ze 4 radku z nekolika stranek, asi bug anebo zmenili layout stranky - take prosim o opravu

3) to by bodlo

A jeste nejake snadne prepnuti na english, pres menu... Slo by?

**Comment by ghubber-zz** [comment]
Myslim bez zavislosti na lokalizaci...

A jeste mi nefunguje vyhledavani a pridani zalozky na Movies, ale to mozna souvisi s mou platformou E2? Verzi mam 1.2.2

**Comment by lukasenkocz** [comment]
Udělal jsem si úpravu souboru sosac.py. která obsahuje žánry. Neorientuji se ale tady na githubu. Mohl bych to někomu poslat do mail na kontrolu a případné doplnění do oficiální distribuce?

**Comment by ghubber-zz** [comment]
Klikni na 

https://github.com/kodi-czsk/plugin.video.sosac.ph/edit/master/resources/lib/sosac.py

A tam to uprav a dole popis komentar

Anebo zmenu napis sem :)

**Comment by lukasenkocz** [comment]
Posílám...
L. Plhoň

---------- Původní zpráva ----------
Od: ghubber notifications@github.com
Komu: kodi-czsk/plugin.video.sosac.ph <plugin.video.sosac.ph@noreply.github.
com>
Datum: 25. 8. 2015 22:37:15
Předmět: Re: [plugin.video.sosac.ph] Nefunkcni nektere serialy + Razeni dle 
zanru? (#18)

"

Klikni na 

https://github.com/kodi-czsk/plugin.video.sosac.ph/edit/master/resources/
lib/sosac.py
(https://github.com/kodi-czsk/plugin.video.sosac.ph/edit/master/resources/lib/sosac.py)

A tam to uprav a dole popis komentar

Anebo zmenu napis sem :)

—
Reply to this email directly or view it on GitHub
(https://github.com/kodi-czsk/plugin.video.sosac.ph/issues/18#issuecomment-134732768)
. 

# "
