### ISSUE TITLE
Plugin přestal fungovat

### ISSUE THREAD

**Issue by chrunda** [kodi-czsk/plugin.video.sosac.ph#26]
Plugin dnes ráno (20.10.2015) přestal fungovat a zobrazuje informace o nelegálnosti.

**Comment by sprattek** [comment]
+1 

je potrebne zaplatit si premium na streamuj.tv ale predpokladam, ze v kodi to aj tak nepofachci :(

**Comment by petrikez** [comment]
Bude plugin nadále funkční?

**Comment by ghost** [comment]
uz sa to raz stalo stale ide tahat flv takze urcite to pojde opravit
https://github.com/lzoubek/xbmc-doplnky/issues/233

**Comment by ToKroCZ** [comment]
Prosím o opravu, evidentně se jedná o již známou chybu viz. Příspěvek nademnou. Přikládám screenshot. 
![screenshot_2015-10-20-20-59-08](https://cloud.githubusercontent.com/assets/11914160/10618104/53aacfd8-776e-11e5-8cbc-c2a468d3067e.png)

**Comment by lzoubek** [comment]
Zdá se, že je vše opět v provozu. Placeni premia vám v kodi nijak nepomůže dokud kluci ze streamujtv neudělají opravdovou podporu přihlášení nebo nedejbože vlastní plugin :+1:

**Comment by petrikez** [comment]
Jo už to jede. Moc děkujeme za rychlou opravu.

**Comment by ghost** [comment]
ide to len docasne info tu https://plus.google.com/112857145614812453402/posts/KpQjxb2AV94

co sa stalo bolo to ze do kodi bola feedovana ina auth ako do firefoxu bohuzial neviem preco momentalne je to ok
priklad:

KODI:
http://www.streamuj.tv/video/998da1d6f943378eecd5?streamuj=original&authorize=e66d6e1f983996e6509c4f009d2e09c3
FIREFOX
http://www.streamuj.tv/video/998da1d6f943378eecd5?streamuj=original&authorize=cf14027f4a8d8a1a98efba0aa548ad85

takze mozme cakat ze budu chciet aby sme platili aj ked pouzivame kodi 
v kazdom pripade potom mame este jednu zalohu v rukave ktora im totalne znemozni blokovanie free pristupu na ich aktualnej platforme (greasemonkey a gatespots)

@lzoubek Libor dufam ze ked to zmenia budete este ochotny plugin opravit aby fungoval
vopred dakujem

**Comment by lzoubek** [comment]
@co5mo uvidime, bude to zalezet na tom s cim prijdou

**Comment by Billysk** [comment]
Preco vlastne pridavanie do kniznice robi strm subor (na Prismcube ruby mi to prehra, na VU+ Solo2 nie a da mi tu obrazovku o nepodporovanom prehravaci), ked by bolo lepsie ulozit do kniznice m3u subor s autorize kodom, ja som si to tak skusil a takto to funguje v KODi v kniznici normalne, akurat som to musel premenovat nachvilu na avi, pridat do kniznice a odmazat avi z databazy a funguje mi to. Nebolo by to lepsie upravit tie strm subory co su na webe za adresu s autorize kodom?
