### ISSUE TITLE
Failed to create directory pri add-to-library

### ISSUE THREAD

**Issue by ghost** [kodi-czsk/plugin.video.sosac.ph#29]
zdravim

hlasi mi pri pridani do library ze nevie vytvorit adresar ale adresar so strm subormi vytvori.

22:01:18 T:992  NOTICE: ('Failed to create directory 2', 'xxx')

taktiez neviem kde by som mohol editovat subscribtion lebo som nastavil add all to library a teraz mi vsetko scanuje a to uz nepotrebujem.

dakujem

log tu
http://pastebin.com/DkH5i7tg

**Comment by lzoubek** [comment]
adresar `C:\\iba taka hra` existuje? muze tam uzivatel co pod nim bezi kodi psat?

editace subscrptions jeste v pluginu neni implementovana.

**Comment by ghost** [comment]
ano aj tam uspesne zapise strm len to vyhodi chybu
deje sa to aj na default directory v profile a aj na androide
chyba sa objavi aj hned ako pridas subs na ktorykolvek serial

android log http://pastebin.com/hEGW2N6x

este otazka co mozem vymazat aky subor/cast suboru aby som zrusil kompletne subs odinstaloval som aj plugin a ked som ho nainstaloval znova zacal checkovat update

dakujem

**Comment by ghost** [comment]
este jedna vec subscription na Agents of S.H.I.E.L.D. generuje nevymazatelny adresar vo windowse lebo konci botkou

da sa vymazat takto cmd

rd /s "\?\C:\Users****\AppData\Roaming\kodi\userdata\addon_data\plugin.video.sosac.ph\TVShows\Agents of S.H.I.E.L.D."

**Comment by lukasenkocz** [comment]
Aktuálně mám problém s importem ze sosáče 1.2.3 do knihovny. Přecházel jsem na na jinou verzi openelec 15.2 a stáhne se mi jen 187 adresářů/souborů strm s filmy. U seriálů se to zdá OK. Nevíte, kde je problém? Ještě jsem to zkoušel ve verzi 14.2, ale v ní to dělá to samé.

**Comment by hetros** [comment]
Mám ten stejný problém co lukasenko na všech 4 svých zařízeních (vše android kodi 15-16). To stejné dělá i známému. Nevyřešil někdo už tento problém?

Diky

**Comment by bbaronSVK** [comment]
[tu](https://github.com/kodi-czsk/plugin.video.sosac.ph/pull/44) by to malo byt uz opravene. Skuste si to ked tak stiahnut z mojho repos.

**Comment by ExSport** [comment]
Dik, ano funguje.
Navic jsem pridal "fix" at nestahuje jen poslednich "182" polozek (Recently Added)...
Kdo ma zajem, je to tu:
https://github.com/kodi-czsk/plugin.video.sosac.ph/pull/44#issuecomment-225424296
