### ISSUE TITLE
Buffering

### ISSUE THREAD

**Issue by maciusko** [kodi-czsk/plugin.video.sosac.ph#36]
Chcel by som sa poradit , v poslednej dobe pri niektorych filmoch stale buffering napriek dostatocnemu internetovemu pripojeniu ...... treba nejako nastavit specialne buffer pre kodi ? alebo pozoruju tento problem aj ostatni ?

dakujem

**Comment by E000001** [comment]
To muze byt treba horsi odezvou serveru, nebo kapacitou po ceste. Buffer se da zvysit. http://kodi.wiki/view/HOW-TO:Modify_the_video_cache
