### ISSUE TITLE
Sony Bravia android tv - nestahuje repozitar doplnkov

### ISSUE THREAD

**Issue by bobina1** [kodi-czsk/plugin.video.sosac.ph#38]
Poprosim o radu,mam tv Sony Bravia s andoid tv. Program kodi som si nainstaloval do tv,ale repozitar doplnkov mi nejde stiahnut do tv a vobec mi ho nechce ani najst v doplnkoch. Pre info,program kodi mam nainstalovany v mobile,tablete aj pc a tam problem nieje vsetko funguje. Dik za pomoc

**Comment by lzoubek** [comment]
Tezko poradit, co je na sony TV za problem, kazdopadne to neni problem doplnku sosac

**Comment by aspiciebam** [comment]
Mám stejný problém. TV mě nechce pustit stáhnout repozitar a nevím co s tim
