### ISSUE TITLE
Diakritika

### ISSUE THREAD

**Issue by hitman222** [kodi-czsk/plugin.video.sosac.ph#4]
Film jak je například Pohádkář Sosáč vůbec nenajde,nedá se to nějak upravit? Tak chyba bude v OpenElec v Kodi na PC mi to našlo.
Dík

**Comment by lzoubek** [comment]
vyzkousej verzi 1.0.2 (update vyjde do hodinky), u me funguje

**Comment by hitman222** [comment]
Tak mne to nejde aktualizovat, pořád píše aktualizace k dispozici ale nestahuje to.
Nakonec jsem to odinstaloval a sosáč nainstaloval ze zipu.
