### ISSUE TITLE
Stahování přestalo fungovat

### ISSUE THREAD

**Issue by m1ngr** [kodi-czsk/plugin.video.sosac.ph#40]
Stahování filmu přestalo fungovat, nyní stáhne pouze html obsah stránky.

Zkoušeno jak RPi2, tak i na Widnows v obou případech Kodi 16

**Comment by ExSport** [comment]
Problem je, ze parser spravne najde video link, ale pak ho spatne posklada do download linku:

```
15:53:05 T:7052  NOTICE: ['Found resolvable http://www.streamuj.tv/video/f2da4c9d8f4a6db23830?remote=1&affid=0&width=960&height=525']
15:53:05 T:7052  NOTICE: [u'Resolving http://www.streamuj.tv/video/f2da4c9d8f4a6db23830?remote=1&affid=0&width=960&height=525']
15:53:05 T:7052  NOTICE: ["Using resolver 'streamujtv'"]
15:53:06 T:7052  NOTICE: [u'Downloading http://movies.prehraj.me//http://www.streamuj.tv/video/f2da4c9d8f4a6db23830?streamuj=original&authorize=12345678901234567890123456789012 to D:\\KODI\\Test\\Happy end (1967).mp4']
```

Neco tam prebyva :)

```
http://movies.prehraj.me//
```

**Comment by jkotvan** [comment]
Ahojte dalo by sa fixnut stahovanie ? Alebo uz tato funkcionalita nebude podporovana ?

Error: 'NoneType' object has no attribute 'close'

**Comment by lzoubek** [comment]
stahovani je dost mozna fixnute ve verzi co je tady na githubu. tato verze jeste nebyla publikovana ven
