### ISSUE TITLE
Raspberry Pi s najnovsim OSMC oznacuje plugin ako nepodporovany/nekompatibilny.

### ISSUE THREAD

**Issue by slavino** [kodi-czsk/plugin.video.sosac.ph#45]
OSMC img.: http://download.osmc.tv/installers/diskimages/OSMC_TGT_rbp2_20160403.img.gz
HW: RPi 2

Po doinstalovani CZ/SK repo plugin neponuka v zozname a po manualnom dotiahnuti cez github vypisuje hlasku o nekompatibilite.

**Comment by lzoubek** [comment]
To muze byt problem verze OSMC, plugin by mel behat na KODI>=14
