### ISSUE TITLE
Nejde prehrat niektore epizody

### ISSUE THREAD

**Issue by buk0** [kodi-czsk/plugin.video.sosac.ph#46]
Kodi neprehra niektore epizody, vsimol som si na seriali Simpsons. Neprehra ako na MacBooku, OpenElecu, ani iPadu. Prilozeny log z MacBook. Epizodu priamo na stranke sosac prehra bez problemov, SD aj HD verziu. 
[kodi_debug_log.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/270191/kodi_debug_log.txt)

**Comment by lzoubek** [comment]
o ktere epizody konkretne se jedna?

**Comment by num3r0** [comment]
Pridavam se se stejnym problemem.
Priklad:
Agents of S.H.I.E.L.D.
S03E12 - OK
S03E13  -nejde ani HD ani SD

Na stejny problem jsem narazil i v pripade filmu:
Tom Clancy's the Division: Agent Origins (2016) - taky nejde ani SD ani HD

Ve vsech pripadech vubec nezacne prehravani. Po vyberu kvality skocim zase v seznamu filmu/serialu.

Pokud je potreba, mohu se pokusit sehnat vice prikladu.

Pouzivam KODI 16.1 (Android)
HW: Minix NEO X8-H Plus (Android 4.4.2, posledni FW)

**Comment by buk0** [comment]
Simpsons S21E08, S21E11, S21E13

**Comment by Veisen** [comment]
nejde konkretne o epizody ale u dějakých serialu se přehraje každý druhý díl jinak hází chybu v logu

např

las vegas casino
zákon gangu 
atd je jich hodně

a jsem si jistý že to je scriptem protože před aktualizací to nebylo

[log.zip](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/353635/log.zip)

**Comment by greedyyy** [comment]
tiez mam problem prehrat niektore filmy.
napr:
nasi sousede jamadovi
ansatsu kyoshitsu

divne je aj to ze napr maly princ bol este nedavno v cestine, pustal som detom, ale v sucasnosti mi to najde iba v eng + sub. 

log 19:39:22 T:6408  NOTICE: ### TVShowTime.com: ['Player.OnStop', '{"end":false,"item":{"title":"Na\xc5\xa1i soused\xc3\xa9 Jamadovi (1999)","type":"movie"}}']
19:39:24 T:4276 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sosac.ph/?play=687474703a2f2f6d6f766965732e7072656872616a2e6d652f63732f706c617965722f6e6173692d736f75736564652d6a616d61646f76692d31393939&cp=736f7361632e7068&
19:39:28 T:11836  NOTICE: ["Initializing provider sosac.ph with settings {'downloads': 'H:\\Nov\xc3\xbd prie\xc4\x8dinok\\', 'quality': '0', 'subs': True}"]
19:39:28 T:11836  NOTICE: ['Found resolvable http://www.streamuj.tv/video/431233287ab1a38fe579?remote=1&affid=0&width=960&height=525']
19:39:28 T:11836  NOTICE: [u'Resolving http://www.streamuj.tv/video/431233287ab1a38fe579?remote=1&affid=0&width=960&height=525']
19:39:28 T:11836  NOTICE: ["Using resolver 'streamujtv'"]
19:39:29 T:11836  NOTICE: ['filtering by quality setting 0']
19:39:33 T:5012   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://www.streamuj.tv/video/431233287ab1a38fe579?streamuj=hd&authorize=97a73f24b67e9ec52624a81c6dbc56e9|Referer=http://www.streamuj.tv/mediaplayer/player.swf|User-Agent=Mozilla/5.0 (X11; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0
19:39:33 T:5012  NOTICE: DVDPlayer: Opening: http://www.streamuj.tv/video/431233287ab1a38fe579?streamuj=hd&authorize=97a73f24b67e9ec52624a81c6dbc56e9|Referer=http://www.streamuj.tv/mediaplayer/player.swf|User-Agent=Mozilla/5.0 (X11; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0
19:39:33 T:5012 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
19:39:33 T:8360  NOTICE: Creating InputStream
19:39:34 T:8360   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://www.streamuj.tv/video/431233287ab1a38fe579?streamuj=hd&authorize=97a73f24b67e9ec52624a81c6dbc56e9|Referer=http://www.streamuj.tv/mediaplayer/player.swf|User-Agent=Mozilla/5.0 (X11; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0
19:40:19 T:8360   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
19:40:19 T:8360  NOTICE: Creating Demuxer
19:40:19 T:8360   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, http://www.streamuj.tv/video/431233287ab1a38fe579?streamuj=hd&authorize=97a73f24b67e9ec52624a81c6dbc56e9
19:40:19 T:8360   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
19:40:19 T:8360  NOTICE: CDVDPlayer::OnExit()
19:40:19 T:5012   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.sosac.ph/?play=687474703a2f2f6d6f766965732e7072656872616a2e6d652f63732f706c617965722f6e6173692d736f75736564652d6a616d61646f76692d31393939&cp=736f7361632e7068&]
19:40:19 T:5012  NOTICE: CDVDPlayer::CloseFile()
19:40:19 T:5012  NOTICE: DVDPlayer: waiting for threads to exit
19:40:19 T:5012  NOTICE: DVDPlayer: finished waiting
19:40:19 T:5012  NOTICE: CDVDPlayer::CloseFile()
19:40:19 T:5012  NOTICE: DVDPlayer: waiting for threads to exit
19:40:19 T:5012  NOTICE: DVDPlayer: finished waiting

**Comment by lzoubek** [comment]
Udelal jsem pokusnou opravu v https://github.com/kodi-czsk/script.module.stream.resolver - zkuste si stahnout master z githubu, prepsat u sebe v addons a testnout

**Comment by greedyyy** [comment]
super, pomohlo.

**Comment by Veisen** [comment]
super problem vyresen dekuji :D

**Comment by buk0** [comment]
fix pomohol. Diky

**Comment by lzoubek** [comment]
ok, pri nejblizsi prilezitosti fix vypublikuju

**Comment by lubo** [comment]
Nove verzie stream resolveru a sosac pluginu vydane. U mna funguje.
