### ISSUE TITLE
sosac zhadzuje kodi na ipad

### ISSUE THREAD

**Issue by greedyyy** [kodi-czsk/plugin.video.sosac.ph#48]
Ipad bez jailbreak, kodi nahrate cez xcode. 
Kodi nahodne pada pri listovani v kniznici sosacu. vyhladavani, prehravani.
do sosacu sa dostanem, nasledny pohyb je loteria.
iny doplnok okrem sosacu kodi nezhadzuje.

**Comment by lubo** [comment]
Logs or die.
