### ISSUE TITLE
chyba 522

### ISSUE THREAD

**Issue by LL75** [kodi-czsk/plugin.video.sosac.ph#51]
Dobrý den,
včera ani dnes jsem se nemohla dostat na stránky, hlásí to chybu 522.
zde screnn.
díky

http://prntscr.com/bjvbn2

**Comment by lzoubek** [comment]
dobry den, 

nejedna se o problem pluginu. Nezbyva nez pockat, nez to provozovatele stranek opravi, nemuzu vam v tom ani pomoct, protoze nikoho z nich neznam.
