### ISSUE TITLE
filmy začínajúce na písmeno s diakritikou

### ISSUE THREAD

**Issue by mino182** [kodi-czsk/plugin.video.sosac.ph#6]
Ahoj, filmy začínajúce na písmeno s diakritikou, nie sú v zozname aj keď na sosáči sú. Napr. "Šéfové na zabití". Díky.

**Comment by hetros** [comment]
Předělal jsem si to sám viz. screenshot. Je to dost jednoduché řešení (s ohledem na omezené možnosti), které by se snadno dalo dodělat do další verze.
![screenshot_2015-06-26-17-02-32](https://cloud.githubusercontent.com/assets/13066617/8380585/f727b1e2-1c26-11e5-80d1-02a829382d61.png)

**Comment by E000001** [comment]
Momentálně se snažím získat od adminů z prehraj.me(dříve sosac.php) XML exporty podle písmen(i s diakritikou) a exporty podle žánrů. Reagují ale dost opožděně, ale vždy odpoví, tak uvídíme :)

**Comment by lukasenkocz** [comment]
Tak to je skvělé. Doplnění prohlížení dle žánrů by bylo velkým přínosem. Ještě by to chtělo i obrázky, ať má člověk aspoň nějakou představu o filmu. V tom velkém množství se těžko orientuje.

**Comment by ghost** [comment]
@E000001 nemyslim si ze su nadseni ze im zadarmo pozerame filmy v minulosti sa snazili aj blokovat prehravanie z kodi

**Comment by tprochazka** [comment]
Mají tam link na IMDB, nešlo by využít toho, že na IMDB plugin už existuje a brát meta informace jako obrázky a popis odtamtud? Ale docela se bojím, že to funguje jen s interním katalogem, je to docela škoda, že ty videa pluginy se nechovají úplně stejně jako interní katalog médií, tedy že se nenaindexuje a nepostahují se covery a nedá se v tom vyhledávat.

**Comment by dodomt** [comment]
Ahojte 

hetros: mohl by si poskytnut zdrojak akosi to urobil mne sa to nedari sjazdnit... dik

dodo

**Comment by hetros** [comment]
dodomt: tady to je:
http://pastebin.com/6nABZADL

**Comment by dodomt** [comment]
Hetros dakujem funguje super ale chyba mi vyhľadávanie ktore je v poslednej verzii sosacu vedel by si to hodiť aj do toho posledného konfigu? Ja to skúšam ale nechce mi to potom načítať filmy a v EN filmoch mi pise failed. Budem skúšať aj dalej Al ak by si to vedel budem vdacny.

dodo

**Comment by E000001** [comment]
Podařilo se mi získat XML exporty pro A-Z(včetně diakritiky) a pro jednotlivé žánry. Akorát jsem jim neříkal pro co to potřebuju, tak snad nám to vydrží :D 
A-Z: http://tv.sosac.to/filmyxmlpismeno.php
Žánry: http://tv.sosac.to/filmyxmlzanr.php

Zatím ale nemám bohužel čas to implementovat do doplňku. :/

**Comment by ghost** [comment]
@E000001 toto tam ale bolo uz dlho dostupne nie? taketo linky pre aff http://tv.prehraj.me/cs/affiliate

**Comment by E000001** [comment]
@co5mo Tam jsou jen XML podle roku a nejnovjěší přidané. Já sem dávám odkazy ještě na XML pro A-Z a XML pro Žánry. Ty prozatím v affiliate nejsou uvedeny. Admin prehraj.me (dříve sosač) to dodělal teď o víkendu.

**Comment by ghost** [comment]
@E000001 aaaha ok super :)

**Comment by sonics007** [comment]
A aky to využiť?

**Comment by lubo** [comment]
@E000001 Nechces ich este poziadat o script pre search ? :smile:

**Comment by E000001** [comment]
Tak jsem s tím zkoušel blbnout několik hodin a vůbec se v tom skriptu nedokážu zorientovat. Moje znalosti Pythonu nejsou na takové úrovni :) Pokud se toho někdo zkušenější ujme, byl bych rád.

@Kuci : No nevím, jestli to pokoušet, oni ani nevědí, že to máme na Kodi :D Viz: https://github.com/kodi-czsk/plugin.video.sosac.ph/issues/6#issuecomment-116594917

**Comment by lubo** [comment]
Toto je uz davno opravene, mohol to niekto zavriet skorej...
