### ISSUE TITLE
Sosac Error - windows

### ISSUE THREAD

**Issue by OstrichTheBird** [kodi-czsk/plugin.video.sosac.ph#61]
prijemny vecer.

od vcera mi nechce ist sosac a chytam error. neviem ci tento problem pretrvava dlhsie ale prihadzujem aj log

Dakujem

[kodilog.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/405816/kodilog.txt)

**Comment by lubo** [comment]
Prosim, zistit verziu script.common.plugin.cache, ktoru pouzivas a napis nam ju sem.

**Comment by OstrichTheBird** [comment]
Blba otazka ale ako to zistim?

Edit: tak nasiel som to a mam 2.5.6

**Comment by lubo** [comment]
Ok, najnovsia verzia je 2.5.8, tak skus prosim upgradnut. Daj potom vediet, ze ci to pomohlo.

**Comment by OstrichTheBird** [comment]
mozem ta poprosit o pomoc ako? lebo nejde mi kliknut na update (je to sede). a netusim ako to upgradovat.

dakujem

**Comment by lubo** [comment]
http://kodi.wiki/view/add-on_manager#Update_options

**Comment by OstrichTheBird** [comment]
aj ked dam check for updates tak sa mi to nechce updatovat. prebehne mi scan ale nic nenajde.

spustit to ako spravca som skusal tiez.

![kodi](https://cloud.githubusercontent.com/assets/20894356/17481079/65c3ed6e-5d7b-11e6-83ae-16259f36a972.png)

**Comment by lubo** [comment]
Aha, tak pardon. script.common.plugin.cache verzia 2.5.8 je dostupna len na Kodi 16. Skus upgradnut Kodi a daj vediet.

**Comment by OstrichTheBird** [comment]
Da sa kodi updatovat aj cez nejaky interny prikaz alebo ako? nikdy som to nerobil takze vobec sa v kodicku nevyznam. som len pasivny uzivatel co to zapne ked chce pozerat film

Edit: Takze kodi som updatol uz mam aj 2.5.8 a stale nejde. prikladam log

[kodilog_2.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/406990/kodilog_2.txt)

**Comment by lubo** [comment]
V skutocnosti je tam o chybu menej. Toto vyzera tak, ze ti nefunguje script.module.stream.resolver. Skus si ho odinstalovat a znova nainstalovat.

**Comment by OstrichTheBird** [comment]
nakoniec som script.module.stream.resolver vobecnemal nainstalovany... uz to ide ^^

dakujem velmi velmi pekne za pomoc :) prajem prijemny zvysok dna :)
