### ISSUE TITLE
Sosáč-pre slovákov len po anglicky?

### ISSUE THREAD

**Issue by karci78** [kodi-czsk/plugin.video.sosac.ph#62]
Dnes som zistil že názvy filmov a seriálov sú v doplnku po anglicky.Pokiaľ si prepnem prostredie na češtinu,názvy sú po česky.....
Viete mi vysvetliť prečo ste na nás slovákov zabudli???? Fakt by som to chcel vedieť ako sa takéto niečo môže stať?myslel som že sú to cz/sk doplnky,nie cz!!!

Fakt nenormálne obdivujem vašu prácu na doplnkoch ako sosáč,befun a podobne a som vám zato vdačný,ale takéto chyby by som fakt nečakal....Dúfam že náprava bude rýchlo na svete....

**Comment by lubo** [comment]
Ok, ak si nie si vedomy toho, ako tato komunita funguje, tak ti to rychlo objasnim - kazdy pracuje na tom, co ho trapi. Ja osobne som slovak a obcas pracujem aj na tomtu doplnku a fakt ma to netrapi, pretoze cele Kodi pouzivam v anglickom jazyku. Predsalen, ta nasa slovencina vobec neznie dobre...

Ak to teba trapi, tak nech sa paci, posli nam pull request a ja osobne ho vdacne mergnem.

**Comment by karci78** [comment]
Som len pasívny užívateľ,ani jednému slovu v poslednej vete som nerozumel.
Ale drvivá väčšina ľudí používa svoj rodný jazyk,pokiaľ je k dispozicíí.
Len som chcel upozorniť na problém,a trochu ma to nahnevalo že sa na slovákov jaksi zabúda,že sme na druhej koľaji...ale ved ja si to teda prepnem na češtinu.

**Comment by lubo** [comment]
Ano, tvoj hnev som tam zbadal a preto som odpovedal ako som odpovedal. Chcem povedat len tolko, ze sa nemusis hnevat. Na slovakov sa ani nezabuda a ani nie su na druhej kolaji. Cesi su na tom vzdy lepsie pretoze su iniciativnejsi nez Slovaci.

V kazdom pripade, @jose1711 sa ukazal ako pravy patriot a prelozil tento plugin do slovenciny. Mozno by sa mohol pozriet aj na toto. Ale Sosac podporuje len anglictinu a cestinu, takze to najlepsie co mozes dostat su ceske nazvy pri pouzivani slovenskeho jazyka.

**Comment by karci78** [comment]
Samozrejme že stačia české názvy,proste aby to bolo tak ako predtým.....Vopred ďakujem za opravu.

**Comment by ExSport** [comment]
https://github.com/kodi-czsk/plugin.video.sosac.ph/pull/63
