### ISSUE TITLE
Sosac 1.2.8 - slovenčina

### ISSUE THREAD

**Issue by sveto99** [kodi-czsk/plugin.video.sosac.ph#64]
Super, že slovenčina je postavená na úroveň češtiny, ale ... chcelo by to možnosť nastaviť, či takúto zmenu užívateľ chce. Teraz, keď dám "Add all to library", tak mi to samozrejme zdvojí "zdroj" a začne znova CSFD popisovať do databázy. (.strm mám teraz v pôvodných názvoch-anglických).
Zmeniť jazyk na English, asi jediné, dúfam že, prechodné riešenie.
Ďakujem inak za skvelú prácu!

**Comment by ExSport** [comment]
Asi nejjednodussi je smazat vsechny strm soubory a dat znovu ADD ALL TO LIBRARY. Stahne se to v cestine, dotaguje se to co jeste KODI nezna a zbytek co je zvojeny se vycisti volbou CLEAN DB v KODI SETTINGS, ktera odstrani neexistujici strm z DB = odstrani pripadne duplicity.
Krok navic, ale logictejsi. Ono se totiz jen v tom jazyce nestahuji strm soubory, ale v tom jazyce se i zobrauji nazvy v Sosaci, proto kdyz si nekdo nastavi EN, ocekava nazvy filmu v EN, pokud CZ/SK, nazvy jsou v cestine (vcetne souboru). Vse se da, ale myslim, ze by se jednalo o zbytecne nastaveni navic matouci neznale...

**Comment by sveto99** [comment]
OK, ďakujem za reakciu. Zmazal som .strm súbory, dal ADD ALL TO LIBRARY, lenže ono to aj tak začalo všetko tagovať odznova ... nie len to, čo KODI nepoznalo :( . Databáza sa odkazuje na daný .strm súbor a pokiaľ ten už nie je, tak taguje odznova. Je pravda, že nie všetky názvy .strm majú "českú" podobu, vtedy k zdvojeniu nedôjde (5 Days of War (2011),6 Years (2015), 11-11-11 (2011) a pod. ...
CLEAN DB je potom konečné riešenie. Ale ten čas!

**Comment by ExSport** [comment]
Ne vsechno, jen to co nezna. Nebude tedy tagovat ceske filmy bez anglickeho nazvu a anglicke nazvy filmu co nemaji ceske ekvivalenty. Je jasne, ze vetsina se bude dotagovavat protoze puvodne se tagovala na anglicky nazev, ted nove na cesky. Ale toto je jen jeden nutny krok, tak se ta reindexace da vydrzet.
A CLEAN DB prave odmaze ty informace na .strm co uz neexistuji, takze procisti tu DB od pripadnych duplicit.
Pro nasledne aktualizace pak uz staci davat ADD ALL TO LIBRARY na polozce "MOVIES Recently Added", ktere drzi posledich 200 zmen.

**Comment by sveto99** [comment]
OK, ďakujem, vyriešené.
