### ISSUE TITLE
Neco chybi a hledani

### ISSUE THREAD

**Issue by Japkozloun** [kodi-czsk/plugin.video.sosac.ph#66]
Ahoj,
takze nejprve diky za fakt super modul pro KODI.
Nektere serialy ktere jsou normalne dostupne na sosac.ph proste chybi (jako treba Dr.house). Druha vec je to, ze vyhledavani (alespon u me) hleda jenom filmy ale serialy uz ne.

**Comment by iChUdY** [comment]
Ahoj,

Dr. House nechybí :P

Hledání na seriály není třeba..

**Comment by petrm74** [comment]
Japkozloun: Zkus hledat anglický název, tedy House M.D.

**Comment by lubo** [comment]
Ahoj, @Japkozloun. Ja som implementoval vyhladavanie a zamerne som ho spravil len pre filmy. Osobne to vidim tak, ze najst danu cast serialu bez vyhladavania nie je problem, ale pri filmoch je situacia odlisna.
