### ISSUE TITLE
Otázka - změna  http HEADERS v Kryptonu

### ISSUE THREAD

**Issue by zbyna** [kodi-czsk/plugin.video.sosac.ph#72]
Bude mít toto:
https://github.com/xbmc/xbmc/pull/9330
vliv na funkčnost stávajícího kódu v Kryptonu ?
Poměrně bouřlivá diskuze se rozhořívá tady: 
http://forum.kodi.tv/showthread.php?tid=280318

**Comment by zbyna** [comment]
@FernetMenta 
`You don't seem to listen. I said standard headers can be passed through without further checks. Non-standard headers can be passed too but require special handling like a user setting to allow those.`

I think it should work

**Comment by zbyna** [comment]
Když tak mě někdo opravte,ale pokud neprojde tento patch 
https://github.com/xbmc/xbmc/pull/10402
myslím, že sosac pod Kryptonem fungovat nebude.

**Comment by Sorien** [comment]
ten PR opravuje iba chybu ked jednotlive streamy v m3u subore nedostanu spravne parametre HEAD/GET requestu, plugin to nijak neovplyvnuje.

**Comment by zbyna** [comment]
Díky za vyjasnění
