### ISSUE TITLE
ako je to s updatami

### ISSUE THREAD

**Issue by sonics007** [kodi-czsk/plugin.video.sosac.ph#73]
Ahojte mohli by ste mi vysvetlit ako je to s updatom v networks vidim 1.2.10
a vkodi mam 1.2.7 .
dakujem za odpoved

**Comment by dvovla** [comment]
To by mne taky moc zajímalo. Díky.

**Comment by lzoubek** [comment]
Vypada to, ze se nam nejak prestaly publikovat nove verze do repa, v repu uz by ted mela byt 1.2.10 - opravim

**Comment by lzoubek** [comment]
opraveno, nyni je v repu 1.2.10
