### ISSUE TITLE
nefunguje na Frodo 12.3

### ISSUE THREAD

**Issue by joazif** [kodi-czsk/plugin.video.sosac.ph#74]
Ahoj,
pouzivam NAS Asustor kde mam xbmc Frodo 12.3 (novejsi tam nejde) a u doplnku sosac 1.2.7  to hlasi :  nefunkcni
Doplnek byl ve zdroji oznacen jako nefunkcni , nesplnene zavislosti
Je mozne s tim neco udelat ?
diky

**Comment by lubo** [comment]
Logs or die.

**Comment by lzoubek** [comment]
Neni, 12.3 uz je hodne stara verze a neni mozne ji podporovat, pokud vim, tak by plugin mel behat na min. 14
