### ISSUE TITLE
new development proposal

### ISSUE THREAD

**Issue by ghost** [kodi-czsk/plugin.video.sosac.ph#76]
@Kuci @lzoubek neuvazovali ste vyuzit plugin exodus a url resolver pri vyvoji tohto pluginu
pridat do exodusu zdroj prehraj.me a do url resolveru streamuj.tv?

exodus ma super integraciu trak.tv na vyhladavanie a jednoduche browsovanie novy filmov.

alebo je to v tejto faze vyvoju uz zbytocne?

https://offshoregit.com/exodus/plugin.video.exodus/
https://github.com/Eldorados/script.module.urlresolver

**Comment by lubo** [comment]
First things first, co je to Exodus ?

**Comment by ghost** [comment]
exodus je asi najoblubenejsi video plugin pre anglicke filmy/serialy ktory scrapuje rozne web stranky a pomocou url resolveru feeduje hosting stranky do kodi takze skoro presne ako sosac

jedina nevyhoda co som si teraz uvedomil ze nema library integraciu ale ma traktv integraciu 
info napr tu http://koditips.com/why-trakt-is-better-than-kodi-library-integration/ 

fork exodusu alebo teda jeho predchodcu genesis s menom specto ma aj integraciu library (funguje na rovnakom principe http://kodi.filmkodi.com/plugin.video.specto/

tieto pluginy funguju tak ze vyhladaju najprv film na strankach nie ako sosac ze priamo celu stranku zobrazia v kodi ale myslim ze aj taky zdroj tam existuje-existoval

uvedomujem si asi ze je to je asi celkom zbytocne ak ludia vyuzivaju library integraciu ktora je aktualne v sosaci uz velmi dobra, mozno by stacilo pridat do sosaca nieco z exodusu ako traktv roky a podobne

**Comment by ghost** [comment]
co pridat z exodus/specto:
- resume points ked spustis film zo strm suboru ponuknut moznost resume kde si skoncil
- traktv integraciu: trending filmy, roky a podobne

skus si nainstalovat exodus/specto a uvidis co dokaze

**Comment by lubo** [comment]
Zas tak moc ma to nezaujima, nakolko nic z toho nepotrebujem. Ja osobne som pri vyvoji toho pluginu moc nebol, len som sa neskor tak trocha ujal jeho maintainovania, nakolko Libor uz vobec nema cas a mne na kvalite toho pluginu zatial velmi zalezi. Ak mas zaujem nieco dorobit, tak kludne posielaj PR.

**Comment by ghost** [comment]
ok rozumiem to bol len taky napad mozno by bolo fajn pustit poslednu verziu sosaca na repo aspon :) dakujem
