### ISSUE TITLE
Nejde prehrat niektore streamy

### ISSUE THREAD

**Issue by buk0** [kodi-czsk/plugin.video.sosac.ph#78]
Dobry den, pri prehravani som prisiel na to, ze kodi neprehra niektore streamy. Konkretne som si to vsimol na Simpsons S24E03, relevantna cast logu prilozena. Aktualna verzia sosac pluginu, rozne platformy ako IOS/Isengard, Windows a Mac/Jarvis. 
[kodi.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/478212/kodi.txt)

**Comment by ghost** [comment]
tiez som si dnes vsimol ze nejde prehrar http://tv.prehraj.me/player/the-simpsons-s10-e13

**Comment by ExSport** [comment]
Pravda, oba priklady nefunguji:
**Sosac v1.2.10
Stream Resolver v1.6.43
Windows KODI 16.1**

**Comment by ghost** [comment]
nefunguje aj http://movies.prehraj.me/player/star-wars-episode-v-the-empire-strikes-back-1980

**Comment by lubo** [comment]
Toto by malo byt opravene v najnovsej verzii stream resolveru. Ak Vam to uz funguje, tak zavrite tuto issue, prosim.

**Comment by ghost** [comment]
wolf of wall street nejde stale ani na najnovsom resolvery napr

**Comment by lubo** [comment]
Oh, to bol zas iny problem. Ten by mal byt fixnuty vo verzii 1.6.47 stream resolveru.

**Comment by buk0** [comment]
Za mna OK, uzatvaram.
