### ISSUE TITLE
sosac strankovanie by bbaronSVK 

### ISSUE THREAD

**Issue by lzoubek** [kodi-czsk/plugin.video.sosac.ph#8]
neslo by spravit do sosaca strankovanie? Neviem ci len ja mam tak slaby komp, ale proste som sa nedostal k ziadnemu zoznamu filmov. Pripadne ak by sa dal dorobit zoznam poslednych pridanych filmov/serialov. Alebo este lepsie vlastne nastavenie pre "vyhladavanie" tak ako to ma uloz.to

**Comment by tprochazka** [comment]
Jo, to jak to teď načítá stovky položek začínající na jedno písmeno je opravdu ukrutně pomalé a určitě to i zatěžuje server a hrozí že budou více usilovat o to Kodi blokovat, možná by to chtělo i delší timeout na cache, aby se stažený seznam držel delší dobu offline.
