### ISSUE TITLE
XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin)

### ISSUE THREAD

**Issue by greedyyy** [kodi-czsk/plugin.video.sosac.ph#82]
zdravim, je to otazka skor na videocesky plugin, ale spytam sa aj tu pretoze problem je takmer rovnaky. 
snazim sa zisti co je to za hlasku a preco ju mam. 
problem mam len s jednym zariadenim na ktorom bezi android 6 (je mozne ze to sposobuje on?)
na nizsich androidoch, windows, ios (aj ked tam to je od verzie kodi 17 alfa sla OK, 17 beta uz neprehra) vratane tohoto stroja pred upgrade to bez problemov prehrava. 
chyba je len an android6

log je plny podobnych hlasok:

 09:19:34 T:18446744072944617776 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.sosac.ph/?play=687474703a2f2f74762e7072656872616a2e6d652f706c617965722f6d6f6465726e2d66616d696c792d73382d653035&cp=736f7361632e7068&

subor sa mi ale  bez problemov otvori a prehra (sosac). 
nanestastie rovnake hlasky v pluginu videa cesky mi subor neprehraju. 

 09:07:05 T:18446744072829155632 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f7468652d6c6174652d73686f772d776974682d7374657068656e2d636f6c626572742d6a616d65732d626f6e642d73692d70726f6e616a696d612d6175746f&cp=76696465616365736b792e637a&

je nejake riesenie? 
problem je aj na kodi 16.1 aj na 17 beta.

**Comment by zbyna** [comment]
Řešení je: 
přidat do xbmcutil.py ve stream resolveru:

``` python
    # odstranuje WARNING: XFILE::CFileFactory::CreateLoader - unsupported
    # protocol(plugin) in plugin://plugin.video.sosac.ph
    li.addStreamInfo('video', {'codec': 'h264',
                               'aspect': 1.78,
                               'width': 1280,
                               'height': 720,
                               'duration': 55})
```

už to mám připravený nějakou dobu, protože mě to v logu taky znervozňovalo :smile: ,  i když to zřejmě ničemu nevadí viz. http://forum.kodi.tv/showthread.php?tid=249697&page=2 
Až a pokud mě projdou pull requesty https://github.com/kodi-czsk/plugin.video.sosac.ph/pull/79  a    https://github.com/kodi-czsk/script.module.stream.resolver/pull/41 
tak připravím samostatný request jenom na tuhle hlášku

**Comment by ExSport** [comment]
@zbyna 
Necekej a nahazuj 👍
