### ISSUE TITLE
Nejdou prehravat serialy.

### ISSUE THREAD

**Issue by hrobar** [kodi-czsk/plugin.video.sosac.ph#88]
Nejdou přehrávat seriály, zobrazí se pouze abeceda a po kliknutí na dané písmeno se zobrazí "Chyba Sosáč více v logu". Pošlu i log, akorát bohužel nevím kde ho najít (přes ssh se umím příhlásit)

**Comment by hrobar** [comment]
Nasel jsem log, pridavam vypis

 `14:13:02 48960.175781 T:1759216624  NOTICE: ['URL: ?cp=736f7361632e7068&list=687474703a2f2f74762e7072656872616a2e6d65']

> 14:13:02 48960.175781 T:1759216624  NOTICE: ["Running sosac provider with params: {'cp': 'sosac.ph', 'list': 'http://tv.prehraj.me'}"]
> 14:13:02 48960.183594 T:1759216624  NOTICE: ["Initializing provider sosac.ph with settings {'downloads': '', 'quality': '0', 'subs': True}"]
> 14:13:02 48960.187500 T:1759216624  NOTICE: ['Examining url http://tv.prehraj.me']
> 14:13:07 48965.652344 T:1759216624  NOTICE: ['URL: ?cp=736f7361632e7068&list=687474703a2f2f74762e7072656872616a2e6d652f63732f74762d73686f77732d612d7a2f302d39']
> 14:13:07 48965.652344 T:1759216624  NOTICE: ["Running sosac provider with params: {'cp': 'sosac.ph', 'list': 'http://tv.prehraj.me/cs/tv-shows-a-z/0-9'}"]
> 14:13:07 48965.664062 T:1759216624  NOTICE: ["Initializing provider sosac.ph with settings {'downloads': '', 'quality': '0', 'subs': True}"]
> 14:13:07 48965.664062 T:1759216624  NOTICE: ['Examining url http://tv.prehraj.me/cs/tv-shows-a-z/0-9']
> 14:13:07 48965.664062 T:1759216624  NOTICE: ['Getting shows by letter http://tv.prehraj.me/cs/tv-shows-a-z/0-9']
> 14:13:08 48966.230469 T:1759216624   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.TypeError'>
>                                             Error Contents: cannot concatenate 'str' and 'list' objects
>                                             Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/plugin.video.sosac.ph/default.py", line 47, in <module>
>                                                 XBMCSosac(SosacContentProvider(reverse_eps=reverse_eps), settings, **addon**).run(params)
>                                               File "/home/osmc/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 66, in run
>                                                 self.list(self.provider.list(params['list']))
>                                               File "/home/osmc/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 195, in list
>                                                 return self.list_tv_shows_by_letter(url)
>                                               File "/home/osmc/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 529, in list_tv_shows_by_letter
>                                                 util.info("Resloved shows " + shows)
>                                             TypeError: cannot concatenate 'str' and 'list' objects
>                                             -->End of Python script error report<--
> 14:13:08 48966.539062 T:1956574128   ERROR: GetDirectory - Error getting plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=687474703a2f2f74762e7072656872616a2e6d652f63732f74762d73686f77732d612d7a2f302d39
> 14:13:08 48966.542969 T:1956574128   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=687474703a2f2f74762e7072656872616a2e6d652f63732f74762d73686f77732d612d7a2f302d39) failed
> 14:23:16 49574.562500 T:1582298096  NOTICE: ['SOSAC Loading subscriptions']
>  `

**Comment by zbyna** [comment]
Na logy se dají použít "ulehčující" doplňky:
http://swski.github.io/kodi-help/

Chyba:

``` python
 ...  File "/home/osmc/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 529, in
 list_tv_shows_by_letter util.info("Resloved shows " + shows) 
TypeError: cannot concatenate 'str' and 'list' objects 
```

bylo opravena https://github.com/kodi-czsk/plugin.video.sosac.ph/pull/87
ale prozatím není  commitnuta v hlavním repo

Jako přechodný řešení by se dala zkusit moje BETA VERZE do které jsem opravu již zahrnul:
https://github.com/zbyna/script.module.stream.resolver
https://github.com/zbyna/plugin.video.sosac.ph
ale můžeš narazit na jiné problémy, které mi mohly uniknout :smiley:

**Comment by hrobar** [comment]
Vypadá to ok, díky moc :)

**Comment by yxus** [comment]
ako ste to prosim dostali do kodi?

**Comment by shckR** [comment]
Zdravím, mám ten samý problém, jen mi řešení od @zbyna nepomohlo. 
http://paste.ubuntu.com/23402536/

**Comment by zbyna** [comment]
@shckR 
Log je zkrácený a záznam o chybě se do něho pravděpodobně nedostal.
Pokud máš stejný problém navržené řešení funguje viz. komentáře zde a v https://github.com/kodi-czsk/plugin.video.sosac.ph/issues/89
Bez úplného logu ti nedokážu říct víc.

**Comment by shckR** [comment]
@zbyna 
Omlouvám se za zkrácený log, dělám to podle návodu viz. http://swski.github.io/kodi-help/
http://paste.ubuntu.com/23403520/
Tento log už vám něco řekne? Díky za pomoc

**Comment by zbyna** [comment]
Díky za úplný log !
Je to ta samá chyba:

``` Python
"C:\Users\Pavel\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", 
line 195, in list
                      return self.list_tv_shows_by_letter(url)
File 
"C:\Users\Pavel\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py",
 line 529, in list_tv_shows_by_letter
                        util.info("Resloved shows " + shows)
   TypeError: cannot concatenate 'str' and 'list' objects
                                            -->End of Python script error report<--
```

tzn. postup uvedený v https://github.com/kodi-czsk/plugin.video.sosac.ph/issues/89 by měl fungovat.
Zkus:
- odinstalovat sosač, (z logu je vidět, že pouštíš pořád původní verzi sosače)
- stáhnout oba dva zip soubory z repozitářů odkazy viz. výše a nainstalovat je.

Pokud to nepomůže, počkej až se změna dostane do masteru sosáče a bude k dispozici jako aktualizace pro všechny. Zbytečně se s tím nemoř, typický ajťák by to asi zvládnul, ale typický ajťák nezvládne plno ostatních věcí 😃  Mluvím z vlastní zkušenosti sám se sebou 😃

**Comment by shckR** [comment]
Díky, problém byl v tom, že jsem vždy nejdřív nainstaloval ten sosáč a pak teprve ty dva soubory :D holt jsem začátečník, díky za pomoc a za čas :)

**Comment by fanysoft** [comment]
To samý, příkládám log
[kodi.zip](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/587664/kodi.zip)
