### ISSUE TITLE
nova instalacia - serialy sosac error

### ISSUE THREAD

**Issue by yxus** [kodi-czsk/plugin.video.sosac.ph#89]
Zdravim, uz asi 4 dni zapasim s novou instalaciou kodi 16.1 a sosac 1.2.11. Vsetko nastavim tak ako treba, ale ked chcem otvorit akykolvek serial vypise mi sosac error, ani nevidim zoznam serialov iba abecedu. Filmy idu bez problemov. Nejde to na win 7 ani na win 10. Pripajam log z win 7.

dakujem za podporu.

[kodi.log.txt](https://github.com/kodi-czsk/plugin.video.sosac.ph/files/556578/kodi.log.txt)

**Comment by zbyna** [comment]
Díky za log ! 

``` python
"C:\Users\Yxus\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", 
line 529, in list_tv_shows_by_letter
           util.info("Resloved shows " + shows)
           TypeError: cannot concatenate 'str' and 'list' objects
```

Jedná se o ten samý problém jako zde:
https://github.com/kodi-czsk/plugin.video.sosac.ph/issues/88
Je tam popsané i přechodné řešení, než bude oprava promítnutá do repozitáře.
Aha, teď jsem si přečetl tvůj poslední comment od tamtéž:
- stáhnout zip soubory s doplňky: odkaz je vždy vpravo nahoře zelený
  Clone or Download/ Download zip
- v Kodi postupně nainstalovat oba stažené zip soubory pomocí:
  Nastavení -> Doplňky -> Instalovat doplněk ze zip archivu.

**Comment by yxus** [comment]
Jo dik moc. Robil som to uz predtym, ale spravalo sa to rovnako, az som uplne odinstaloval povodny sosac a nainstaloval len opravene doplnky, uz to funguje. Super. Ale vsimol som si, ze sa mi filmy/serialy podari spustit az na druhy krat - prvy krat mi to vzdy vypise, ze subor bol odstraneny. To ale nevadi, este raz diky.

**Comment by lzoubek** [comment]
Prosim otestuj na verzi 1.3.0 a pripadne otevri novou issue
