### ISSUE TITLE
problem s listovanim pismena T (eng)

### ISSUE THREAD

**Issue by ghost** [kodi-czsk/plugin.video.sosac.ph#9]
zdravim libor

pouzivam sosac addon kde je este jazyk english, pri listovani pismena T nastane problem
vsetky pismena idu toto pismeno asi obsahuje vela filmov a plugin to nezvladne...
(scrapujem strm a potrebujem anglicke nazvy)

ked som skusil plugin ktory ma cz nazvy T pismeno ide ok

posielam log
http://pastebin.com/0F9NeH6e

prikladam aj upraveny sosac.py
(je to predosla verzia ktora zobrazuje eng nazvy ale ma zmenene base_url)
http://pastebin.com/raw.php?i=Swj7U0n7

dakujem za pomoc
f.

**Comment by ghost** [comment]
ehm... trosku som poguglil a tu je fix
v pismene t je aktualne 1962 filmov a default limit je 1000 preto ta chyba...

treba pridat do kodu 

import sys
sys.setrecursionlimit(10000)

**Comment by lzoubek** [comment]
ahoj, recursion limit pridam. Ohledne volby jazyka, nechci aby tridy, ktere dedi z ContentProvider jakymkoliv zpusobem importovali neco z xbmc (viz tvuj prilozeny sosac.py). Dany ContentProvider potom nelze nezavisle testovat ani behat mimo xbmc.

Pridam obecnou podporu pro ziskani aktualniho jazyku pro vsechny pluginy do stream.resolver modulu

**Comment by lzoubek** [comment]
Diky za opravu
