### ISSUE TITLE
Chybí Krteček

### ISSUE THREAD

**Issue by Ryesen** [kodi-czsk/plugin.video.sosac.ph#94]
Dobrý den,
na stránkách sosac je k dispozici krteček ( tv.sosac.tv/cs/detail/krtek), bohužel v kodi ho nevidím. prosím o opravu :-)

**Comment by lzoubek** [comment]
Je treba mit globalne v kodi nastavenou cestinu. Nyni ma plugin v nastaveni moznost zaskrtnuti "Cestina", nevim, k cemu to tam kdo dal, ale upravim ho tak, ze bude-li to zaple, bude se ignorovat globalni lokalizace kodi

**Comment by Ryesen** [comment]
Globální nastavení jazyka se nastavuje zde? `https://www.tvaddons.ag/kodi-language/`

**Comment by lzoubek** [comment]
presne tak

**Comment by Ryesen** [comment]
Ok, tak změněno na Czech a kodování Výchozí. Seriál **Krtek** vidím, bohužel neobsahuje žádné díly. @lzoubek : Nějaký tip?

**Comment by lzoubek** [comment]
Opraveno v 1.3.0
