### ISSUE TITLE
cloundflare

### ISSUE THREAD

**Issue by ghost** [kodi-czsk/plugin.video.sosac.ph#96]
ahojte cloudflare ochrana neumoznuje asi scrape stranky momentalne nic nevidim v logu

**Comment by lubo** [comment]
Ano, uz som si toho vsimol. Stranka hadze status code 503 s validnym HTML. Riesenie by malo byt ale pomerne nenarocne. Malo by stacit nastavit cookie `__cfduid` podla requestu a potom sa presunut na URL specifikovanu v `Refresh` headery. Toto by malo stacit spravit pri spusteni pluginu a dalej len pouzivat tu cookie. Kto chce to moze skodit, ja som busy.

**Comment by bbaronSVK** [comment]
az take jednoduche to asi nebude podla https://github.com/Anorov/cloudflare-scrape sa tam spusta vygenerovany JS ... ale este som nemal na to cas. Ak by to niekto riesil, tak dajte vediet, aby na tom nerobilo viacero ludi ;-)

**Comment by pio4ADay** [comment]
Sosac presunul svoje servery z sosac.ph na sosac.tv. Sorry kodovani nerozumim vubec ( jsem rad ze zakoduju alarm u baraku ) ale ziju 20tisic km od domova a sosac je snad to nejcennejsi co na kodi pro me existuje. Muze nekdo po-opravit ten add-on do funkcniho stavu.?

**Comment by co5mo** [comment]
@pio4ADay no to nieje sosac ale ok :) to je niekto kto len okopiroval stranku

**Comment by mino182** [comment]
Ak by vám to mohlo pomôcť, tu je dočasné riešenie od Radka z G+:
Tak pokud máte zájem o experimentální patch (zatím si neumí 'poznačit', že prošel skrz cloudflare ochranu, a prochází ji tedy znovu a znovu při načtení každé položky v menu), tady je i s mininávodem, jak na to:

1) nainstalovat cloudflare-scrape pomocí návodu na https://github.com/Anorov/cloudflare-scrape (sekce Installation)
2) nahradit soubor sosac.py (plugin.video.sosac.ph/resources/lib/sosac.py) souborem z http://pastebin.com/raw/D8WwKcr0 (můj experimentální patch)
3) smazat soubor commoncache.db (.kodi/temp/commoncache.db)
4) restartovat kodi

**Comment by pio4ADay** [comment]
Hahaha.. OK..sry vid..alespon vidis jakej jsem noob. :) Me sosac prestal fachat vcera rano ( predevcirem vecer evropskeho casu ). Pak mi zase zacal fachat a bylo to v pohode celej vecer a ted rano zase nic. Vcera se mi  prazdny movies a tv shows folders postupne zase zacali loadovat jak to bylo pred tim. Rano zase prazdno.

**Comment by ghost** [comment]
@mino182 dakujem ale tu aj ludia pouzivaju android boxy k tv potrebujeme nieco bez toho cloudflare-scrape aj

**Comment by pio4ADay** [comment]
Jo Jo...ja jedu raspberry pi... Takze asi bude potreba more general solution.

**Comment by co5mo** [comment]
btw keby mal dakdo zaujem o free sosac/prehraj.me/streamuj.tv bez kodi len priamo cez browser staci ked sem napise

**Comment by pio4ADay** [comment]
@co5mo pio4aday@gmail.com

**Comment by ghost** [comment]
Stream All the Sources addon scrapuje cez cloudflare sam osebe bez problemov a ma to vyriesene source tu aj 

https://github.com/tknorris/tknorris-beta-repo/blob/master/zips/plugin.video.salts/plugin.video.salts-2.0.85.zip

py tu http://pastebin.com/07aJckyC

**Comment by lubo** [comment]
@co5mo @pio4ADay Chalani, toto nie je zoznamka... Prosim, iba k veci a vsetko ostatne, co nechcete darovat komunite ako celku si rieste prosim inde.

**Comment by lubo** [comment]
@bbaronSVK Vies poskytnut nejaky feedback na #98 ?

**Comment by mino182** [comment]
inak na domene sosac.tv cloudflare nie je. Keď zmením base_url adresy v sosac.py tak funguje vyhľadávanie aj prehrávanie filmov. Bez akejkoľvek inej úpravy. Akurát filmyxmlpismeno.php má buď iný názov, alebo cestu, takže a-to-z nefunguje.

**Comment by lubo** [comment]
@mino182 A je sosac.tv stranka s tym istym obsahom ? Vzdy aktualnym ?

**Comment by mino182** [comment]
myslím, že áno.

**Comment by mino182** [comment]
úvodný slider je rovnaký, "Nově přidané" a "Novinky" sú zhodné...

Edit:
tak tá doména určite smeruje na ten istý web - overil som si to cez účet...

**Comment by pio4ADay** [comment]
Ja to rikal.

**Comment by bbaronSVK** [comment]
sosac.tv je tiez na CF, takze je len otazka casu, kedy zapnu ochranu aj tam.
```
# dig tv.sosac.tv +short
104.18.49.168
104.18.48.168
```
```
# traceroute 104.18.48.168
...
10  cloudflare.peering.cz (91.213.211.102)  12.033 ms  12.051 ms  12.067 ms
11  104.18.48.168 (104.18.48.168)  11.627 ms  11.576 ms  11.533 ms
```
Jedina moznost je teda prelomit ochranu a myslim, ze ```plugin.video.salts``` by to uz malo ist v pohode.

@Lubo ak sa ta #98 mergne, tak to podla mna tiez nepojde, lebo je docela mozne, ze to server proste nezvladne servovat (moja osobna skusenost so sosacom) a to moj server nieje az taka sracka: 8xi7-4770 CPU @ 3.40GHz s 32G RAM

Tiez pouzivam CF na iny KODI plugin, ale ochranu som tam nezapinal, lebo je to platena sluzba. Takze si myslim, ze tu ochranu budu pustat len na vecer, alebo len po urcitu dobu, potom im trial vyprsi a budu musiet zacat platit, co sa im asi moc neoplati.

Snad #99 pomoze ;-)

**Comment by bbaronSVK** [comment]
Ak to niekto naformatuje :D na to ja nemam nervy ;-)

**Comment by bbaronSVK** [comment]
Ok, tak ochrana by mala byt prekonana ... uz len to skontrolovat a nasadit

**Comment by lubo** [comment]
Myslim, ze toto uz nemusime dalej riesit a zatvaram to tu v prospech #102.
